INSERT INTO IDIOMA (codigo_iso, nombre) VALUES
  ('en', 'Inglés'),
  ('es', 'Español'),
  ('fr', 'Francés'),
  ('de', 'Alemán'),
  ('it', 'Italiano'),
  ('pt', 'Portugués'),
  ('zh', 'Mandarín'),
  ('ja', 'Japonés'),
  ('ko', 'Coreano'),
  ('ru', 'Ruso'),
  ('ar', 'Árabe'),
  ('hi', 'Hindi'),
  ('bn', 'Bengalí'),
  ('ur', 'Urdu'),
  ('tr', 'Turco'),
  ('nl', 'Holandés'),
  ('sv', 'Sueco'),
  ('no', 'Noruego'),
  ('da', 'Danés'),
  ('fi', 'Finlandés'),
  ('el', 'Griego'),
  ('pl', 'Polaco'),
  ('cs', 'Checo'),
  ('hu', 'Húngaro'),
  ('he', 'Hebreo'),
  ('th', 'Tailandés'),
  ('vi', 'Vietnamita'),
  ('id', 'Indonesio'),
  ('ms', 'Malayo'),
  ('sw', 'Swahili'),
  ('yo', 'Yoruba'),
  ('zu', 'Zulú'),
  ('am', 'Amárico'),
  ('ha', 'Hausa'),
  ('ig', 'Igbo'),
  ('tl', 'Tagalo'),
  ('ta', 'Tamil'),
  ('lo', 'Lao'),
  ('my', 'Birmano'),
  ('ro', 'Rumano'),
  ('uk', 'Ucraniano'),
  ('sr', 'Serbio'),
  ('sk', 'Eslovaco'),
  ('lt', 'Lituano'),
  ('lv', 'Letón'),
  ('et', 'Estonio'),
  ('qu', 'Quechua'),
  ('gn', 'Guaraní'),
  ('ay', 'Aimara'),
  ('mi', 'Maorí'),
  ('sm', 'Samoano'),
  ('fj', 'Fiyiano'),
  ('eo', 'Esperanto');

INSERT INTO FORMATO (nombre, descripcion) VALUES
  ('MP4', 'Formato de archivo multimedia comprimido que es ampliamente utilizado para transmisión de video en línea'),
  ('MKV', 'Formato contenedor de video que admite múltiples pistas de audio y subtítulos'),
  ('AVI', 'Formato contenedor de video desarrollado por Microsoft'),
  ('MOV', 'Formato de archivo multimedia desarrollado por Apple para QuickTime'),
  ('WEBM', 'Formato de archivo multimedia abierto y gratuito desarrollado para la web'),
  ('FLV', 'Formato de archivo Flash Video, ampliamente utilizado para transmisión de video en línea'),
  ('WMV', 'Formato de archivo desarrollado por Microsoft para Windows Media'),
  ('OGG', 'Formato de archivo multimedia contenedor abierto y gratuito'),
  ('HLS', 'Protocolo de transmisión de video HTTP Live Streaming utilizado para la entrega de contenido multimedia a través de Internet'),
  ('MPEG-DASH', 'Estándar para la transmisión adaptativa de video a través de HTTP'),
  ('AAC', 'Formato de compresión de audio avanzado, comúnmente utilizado para transmisión de audio en línea'),
  ('MP3', 'Formato de compresión de audio comúnmente utilizado para transmisión de audio en línea');

INSERT INTO CONTINENTE (nombre, descripcion) VALUES
  ('África', 'El segundo continente más grande de la Tierra, conocido por su diversidad cultural, su vida salvaje y sus paisajes impresionantes.'),
  ('América', 'El continente donde se encuentra la mayor parte de la cordillera de los Andes y el lago Titicaca, conocido por su diversidad geográfica y cultural.'),
  ('Asia', 'El continente más grande y poblado del mundo, conocido por su historia antigua, su tecnología avanzada y su diversidad cultural.'),
  ('Europa', 'El continente donde se encuentra la mayor parte de la península balcánica y los Alpes, conocido por su historia, su arte y su diversidad lingüística.'),
  ('Oceanía', 'El continente más pequeño del mundo, conocido por su gran cantidad de islas, su vida marina y sus paisajes paradisíacos.');

INSERT INTO PAIS (nombre, descripcion, id_continente) VALUES
  ('Angola', 'País en África, conocido por su diversidad étnica y sus recursos naturales.', 1),
  ('Argelia', 'País en África del Norte, conocido por su desierto del Sáhara y su historia.', 1),
  ('Benín', 'País en África Occidental, conocido por su rica historia y su cultura vudú.', 1),
  ('Botsuana', 'País en África Austral, conocido por su vida salvaje y su estabilidad política.', 1),
  ('Burkina Faso', 'País en África Occidental, conocido por su música y su paisaje variado.', 1),
  ('Burundi', 'País en África Central, conocido por su historia colonial y sus problemas sociales.', 1),
  ('Cabo Verde', 'País insular en África, conocido por sus playas y su música.', 1),
  ('Camerún', 'País en África Central, conocido por su diversidad cultural y su vida salvaje.', 1),
  ('Chad', 'País en África Central, conocido por su paisaje desértico y sus tribus nómadas.', 1),
  ('Comoras', 'País insular en África, conocido por sus playas de arena blanca y su cultura.', 1),
  ('Congo', 'País en África Central, conocido por su biodiversidad y sus recursos naturales.', 1),
  ('Costa de Marfil', 'País en África Occidental, conocido por su producción de cacao y su música.', 1),
  ('Egipto', 'País en África del Norte, conocido por su historia antigua y sus monumentos.', 1),
  ('Eritrea', 'País en África del Este, conocido por su independencia reciente y su diversidad étnica.', 1),
  ('Etiopía', 'País en África del Este, conocido por su historia antigua y su cultura.', 1),
  ('Gabón', 'País en África Central, conocido por su vida salvaje y sus parques nacionales.', 1),
  ('Gambia', 'País en África Occidental, conocido por su río y su ambiente relajado.', 1),
  ('Ghana', 'País en África Occidental, conocido por su historia colonial y su democracia.', 1),
  ('Guinea', 'País en África Occidental, conocido por su diversidad étnica y su vida salvaje.', 1),
  ('Guinea-Bisáu', 'País en África Occidental, conocido por su historia colonial y su vida rural.', 1),
  ('Guinea Ecuatorial', 'País en África Central, conocido por su producción de petróleo y su biodiversidad.', 1),
  ('Kenia', 'País en África del Este, conocido por su vida salvaje y sus paisajes naturales.', 1),
  ('Lesoto', 'País en África Austral, conocido por su altitud y sus paisajes montañosos.', 1),
  ('Liberia', 'País en África Occidental, conocido por ser fundado por esclavos liberados.', 1),
  ('Libia', 'País en África del Norte, conocido por su desierto del Sáhara y su historia antigua.', 1),
  ('Madagascar', 'País insular en África, conocido por su biodiversidad única y su cultura.', 1),
  ('Malaui', 'País en África Oriental, conocido por su lago y su vida salvaje.', 1),
  ('Malí', 'País en África Occidental, conocido por su historia imperial y su desierto.', 1),
  ('Marruecos', 'País en África del Norte, conocido por su mezcla de influencias culturales.', 1),
  ('Mauricio', 'País insular en África, conocido por sus playas y su industria turística.', 1),
  ('Mauritania', 'País en África del Oeste, conocido por su desierto del Sáhara y su cultura nómada.', 1),
  ('Mozambique', 'País en África Oriental, conocido por su costa y su vida salvaje.', 1),
  ('Namibia', 'País en África Austral, conocido por su desierto y su vida salvaje.', 1),
  ('Níger', 'País en África Occidental, conocido por su desierto del Sáhara y su vida nómada.', 1),
  ('Nigeria', 'País en África Occidental, conocido por su población y su industria petrolera.', 1),
  ('República Centroafricana', 'País en África Central, conocido por su vida salvaje y sus conflictos civiles.', 1),
  ('República Democrática del Congo', 'País en África Central, conocido por su biodiversidad y sus conflictos.', 1),
  ('Ruanda', 'País en África Oriental, conocido por su historia reciente y su desarrollo.', 1),
  ('Santo Tomé y Príncipe', 'País insular en África, conocido por sus playas y su biodiversidad.', 1),
  ('Senegal', 'País en África Occidental, conocido por su cultura y su democracia.', 1),
  ('Seychelles', 'País insular en África, conocido por sus playas y su industria turística.', 1),
  ('Sierra Leona', 'País en África Occidental, conocido por su historia colonial y su vida salvaje.', 1),
  ('Somalia', 'País en África del Este, conocido por sus conflictos y su vida salvaje.', 1),
  ('Suazilandia', 'País en África Austral, conocido por su cultura y su vida salvaje.', 1),
  ('Sudáfrica', 'País en África Austral, conocido por su diversidad cultural y su historia.', 1),
  ('Sudán', 'País en África del Norte, conocido por su historia antigua y sus conflictos recientes.', 1),
  ('Sudán del Sur', 'País en África Oriental, conocido por ser el país más nuevo del mundo.', 1),
  ('Tanzania', 'País en África Oriental, conocido por su vida salvaje y sus paisajes.', 1),
  ('Togo', 'País en África Occidental, conocido por su historia colonial y su cultura vudú.', 1),
  ('Túnez', 'País en África del Norte, conocido por su historia antigua y sus playas.', 1),
  ('Uganda', 'País en África Oriental, conocido por su diversidad étnica y su vida salvaje.', 1),
  ('Yibuti', 'País en África del Este, conocido por su ubicación estratégica y su puerto.', 1),
  ('Zambia', 'País en África Austral, conocido por sus parques nacionales y su vida salvaje.', 1),
  ('Zimbabue', 'País en África Oriental, conocido por sus ruinas antiguas y su vida salvaje.', 1),

  ('Estados Unidos', 'País en América del Norte, conocido por su diversidad cultural y sus ciudades.', 2),
  ('Canadá', 'País en América del Norte, conocido por su naturaleza expansiva y su calidad de vida.', 2),
  ('México', 'País en América del Norte, conocido por su rica cultura y su comida.', 2),
  ('Cuba', 'País insular en el Caribe, conocido por su música, su historia y sus playas.', 2),
  ('Guatemala', 'País en América Central, conocido por su rica historia maya y su diversidad étnica.', 2),
  ('Costa Rica', 'País en América Central, conocido por su biodiversidad y sus áreas protegidas.', 2),
  ('Panamá', 'País en América Central, conocido por el Canal de Panamá y su biodiversidad.', 2),
  ('República Dominicana', 'País en el Caribe, conocido por sus playas y su música.', 2),
  ('Honduras', 'País en América Central, conocido por sus ruinas mayas y sus parques nacionales.', 2),
  ('El Salvador', 'País en América Central, conocido por sus volcanes y su historia colonial.', 2),
  ('Brasil', 'País en América del Sur, conocido por su tamaño y su diversidad cultural.', 2),
  ('Argentina', 'País en América del Sur, conocido por su cultura del tango y sus paisajes.', 2),
  ('Colombia', 'País en América del Sur, conocido por su café y su biodiversidad.', 2),
  ('Perú', 'País en América del Sur, conocido por Machu Picchu y su gastronomía.', 2),
  ('Venezuela', 'País en América del Sur, conocido por su petróleo y su diversidad geográfica.', 2),
  ('Chile', 'País en América del Sur, conocido por sus paisajes y su vino.', 2),
  ('Ecuador', 'País en América del Sur, conocido por las Islas Galápagos y su diversidad étnica.', 2),
  ('Bolivia', 'País en América del Sur, conocido por su altiplano y su cultura indígena.', 2),
  ('Paraguay', 'País en América del Sur, conocido por el río Paraguay y su historia.', 2),
  ('Uruguay', 'País en América del Sur, conocido por su carne y su costa.', 2),
  ('Nicaragua', 'País en América Central, conocido por sus lagos y volcanes.', 2),
  ('Belice', 'País en América Central, conocido por su rica biodiversidad y sus ruinas mayas.', 2),
  ('Jamaica', 'País en el Caribe, conocido por su música reggae y sus playas.', 2),
  ('Haití', 'País en el Caribe, conocido por su historia colonial y sus desafíos económicos.', 2),
  ('Trinidad y Tobago', 'País insular en el Caribe, conocido por su diversidad étnica y su petróleo.', 2),
  ('Barbados', 'País insular en el Caribe, conocido por sus playas y su cultura.', 2),
  ('Bahamas', 'País insular en el Caribe, conocido por sus hermosas islas y sus aguas cristalinas.', 2),
  ('Guyana', 'País en América del Sur, conocido por su selva tropical y su diversidad étnica.', 2),
  ('Surinam', 'País en América del Sur, conocido por su diversidad cultural y su riqueza natural.', 2),
  ('Antigua y Barbuda', 'País insular en el Caribe, conocido por sus playas y su historia colonial.', 2),
  ('San Cristóbal y Nieves', 'País insular en el Caribe, conocido por su belleza natural y su tranquilidad.', 2),
  ('Santa Lucía', 'País insular en el Caribe, conocido por sus montañas y sus playas.', 2),
  ('San Vicente y las Granadinas', 'País insular en el Caribe, conocido por sus islas paradisíacas y su cultura.', 2),
  ('Granada', 'País insular en el Caribe, conocido por su belleza natural y su historia colonial.', 2),
  ('Dominica', 'País insular en el Caribe, conocido por su belleza natural y sus montañas.', 2),

  ('China', 'País en Asia, conocido por su población y su historia antigua.', 3),
  ('India', 'País en Asia, conocido por su diversidad cultural y su economía en crecimiento.', 3),
  ('Indonesia', 'País en Asia, conocido por su archipiélago y su diversidad étnica.', 3),
  ('Pakistán', 'País en Asia, conocido por su historia antigua y su diversidad religiosa.', 3),
  ('Bangladesh', 'País en Asia, conocido por su población y sus desafíos económicos.', 3),
  ('Japón', 'País en Asia, conocido por su tecnología avanzada y su cultura tradicional.', 3),
  ('Filipinas', 'País insular en Asia, conocido por sus hermosas playas y su diversidad étnica.', 3),
  ('Vietnam', 'País en Asia, conocido por su historia colonial y su hermoso paisaje.', 3),
  ('Irán', 'País en Asia, conocido por su historia antigua y su riqueza cultural.', 3),
  ('Turquía', 'País en Asia y Europa, conocido por su ubicación estratégica y su rica historia.', 3),
  ('Rusia', 'País en Europa y Asia, conocido por su extensión territorial y su historia.', 3),
  ('Corea del Sur', 'País en Asia, conocido por su desarrollo económico y su cultura pop.', 3),
  ('Arabia Saudita', 'País en Asia, conocido por su riqueza petrolera y su religión dominante.', 3),
  ('Irak', 'País en Asia, conocido por su historia antigua y sus conflictos modernos.', 3),
  ('Afganistán', 'País en Asia, conocido por su historia turbulenta y sus desafíos políticos.', 3),
  ('Tailandia', 'País en Asia, conocido por sus playas y su cultura budista.', 3),
  ('Taiwán', 'Isla en Asia, conocida por su tecnología y su disputa política con China.', 3),
  ('Sri Lanka', 'Isla en Asia, conocida por sus playas y su patrimonio cultural.', 3),
  ('Malasia', 'País en Asia, conocido por su diversidad étnica y sus paisajes.', 3),
  ('Singapur', 'Ciudad-estado en Asia, conocida por su desarrollo económico y su limpieza.', 3),
  ('Uzbekistán', 'País en Asia Central, conocido por su historia en la Ruta de la Seda y sus monumentos antiguos.', 3),
  ('Yemen', 'País en Asia, conocido por su historia antigua y sus conflictos actuales.', 3),
  ('Nepal', 'País en Asia, conocido por su paisaje montañoso y el monte Everest.', 3),
  ('Siria', 'País en Asia, conocido por su historia antigua y su conflicto civil.', 3),
  ('Camboya', 'País en Asia, conocido por sus templos antiguos y su historia.', 3),
  ('Omán', 'País en Asia, conocido por su riqueza petrolera y su belleza natural.', 3),
  ('Qatar', 'País en Asia, conocido por su riqueza petrolera y su desarrollo urbano.', 3),
  ('Kuwait', 'País en Asia, conocido por su riqueza petrolera y su desarrollo económico.', 3),
  ('Líbano', 'País en Asia, conocido por su historia antigua y su diversidad cultural.', 3),
  ('Israel', 'País en Oriente Medio, conocido por su historia religiosa y sus tensiones políticas.', 3),
  ('Mongolia', 'País en Asia, conocido por sus vastas estepas y su historia nómada.', 3),
  ('Jordania', 'País en Asia, conocido por Petra y su historia antigua.', 3),
  ('Emiratos Árabes Unidos', 'País en Asia, conocido por su desarrollo urbano y su riqueza petrolera.', 3),
  ('Laos', 'País en Asia, conocido por su belleza natural y su cultura tradicional.', 3),
  ('Kirguistán', 'País en Asia Central, conocido por su paisaje montañoso y sus lagos.', 3),
  ('Bangladés', 'País en Asia, conocido por su densa población y sus desafíos económicos.', 3),
  ('Azerbaiyán', 'País en Asia occidental, conocido por su cultura y sus paisajes montañosos.', 3),
  ('Bahréin', 'Pequeño país insular en Asia, conocido por su economía basada en el petróleo y su arquitectura moderna.', 3),
  ('Bután', 'País en Asia, conocido por su enfoque en la felicidad nacional bruta y su impresionante paisaje montañoso.', 3),
  ('Brunéi', 'País en Asia, conocido por su riqueza petrolera y su sistema político.', 3),
  ('Maldivas', 'País insular en Asia, conocido por sus hermosas playas y sus resorts de lujo.', 3),
  ('Tayikistán', 'País en Asia Central, conocido por su paisaje montañoso y sus antiguas rutas comerciales.', 3),
  ('Timor Oriental', 'País en Asia, conocido por su historia reciente de independencia y sus playas vírgenes.', 3),
  ('Turkmenistán', 'País en Asia Central, conocido por su régimen político autoritario y su vasta reserva de gas natural.', 3),

  ('Albania', 'País en Europa, conocido por su rica historia y sus paisajes montañosos.', 4),
  ('Alemania', 'País en Europa, conocido por su economía potente y su cultura.', 4),
  ('Andorra', 'Pequeño país en Europa, conocido por sus estaciones de esquí y su paisaje montañoso.', 4),
  ('Austria', 'País en Europa, conocido por su arte, su música clásica y sus paisajes alpinos.', 4),
  ('Bélgica', 'País en Europa, conocido por su chocolate, su cerveza y su arquitectura medieval.', 4),
  ('Bielorrusia', 'País en Europa del Este, conocido por su historia y su arquitectura soviética.', 4),
  ('Bosnia y Herzegovina', 'País en Europa, conocido por sus paisajes naturales y su historia complicada.', 4),
  ('Bulgaria', 'País en Europa del Este, conocido por su rica historia y sus playas en el Mar Negro.', 4),
  ('Chipre', 'Isla en el Mar Mediterráneo, conocida por su historia antigua y sus playas.', 4),
  ('Croacia', 'País en Europa, conocido por su costa adriática y sus parques nacionales.', 4),
  ('Dinamarca', 'País en Europa, conocido por su diseño, su calidad de vida y sus islas.', 4),
  ('Eslovaquia', 'País en Europa Central, conocido por su patrimonio histórico y sus montañas.', 4),
  ('Eslovenia', 'País en Europa Central, conocido por su belleza natural y su calidad de vida.', 4),
  ('España', 'País en Europa, conocido por su diversidad cultural y su clima.', 4),
  ('Estonia', 'País en Europa del Norte, conocido por su tecnología avanzada y su belleza natural.', 4),
  ('Finlandia', 'País en Europa del Norte, conocido por su diseño, su educación y su naturaleza.', 4),
  ('Francia', 'País en Europa, conocido por su cultura, su gastronomía y su historia.', 4),
  ('Grecia', 'País en Europa, conocido por su historia antigua, sus islas y su comida mediterránea.', 4),
  ('Hungría', 'País en Europa Central, conocido por sus baños termales y su rica historia.', 4),
  ('Irlanda', 'País en Europa, conocido por sus paisajes verdes, su música y su historia.', 4),
  ('Islandia', 'País insular en Europa del Norte, conocido por su naturaleza virgen y sus paisajes espectaculares.', 4),
  ('Italia', 'País en Europa, conocido por su arte, su historia y su comida.', 4),
  ('Letonia', 'País en Europa del Norte, conocido por su belleza natural y su historia.', 4),
  ('Liechtenstein', 'Pequeño país en Europa, conocido por su paisaje montañoso y su industria financiera.', 4),
  ('Lituania', 'País en Europa del Norte, conocido por su historia y sus bosques.', 4),
  ('Luxemburgo', 'País en Europa, conocido por su economía estable y su multiculturalidad.', 4),
  ('Malta', 'País insular en el Mar Mediterráneo, conocido por su historia y sus playas.', 4),
  ('Moldavia', 'País en Europa del Este, conocido por su historia y su diversidad étnica.', 4),
  ('Mónaco', 'Pequeño país en Europa, conocido por su glamour y su famoso casino.', 4),
  ('Montenegro', 'País en Europa, conocido por sus montañas, su costa y su historia.', 4),
  ('Noruega', 'País en Europa del Norte, conocido por sus fiordos, su calidad de vida y su petróleo.', 4),
  ('Países Bajos', 'País en Europa, conocido por sus tulipanes, sus molinos y su tolerancia.', 4),
  ('Polonia', 'País en Europa, conocido por su historia medieval y su resistencia durante la Segunda Guerra Mundial.', 4),
  ('Portugal', 'País en Europa, conocido por su historia marítima, su vino y su fado.', 4),
  ('Reino Unido', 'País insular en Europa, conocido por su historia y su monarquía.', 4),
  ('República Checa', 'País en Europa Central, conocido por su arquitectura, su cerveza y su historia.', 4),
  ('Rumania', 'País en Europa, conocido por su rica historia y sus paisajes montañosos.', 4),
  ('San Marino', 'Pequeño país en Europa, conocido por su historia y su independencia.', 4),
  ('Serbia', 'País en Europa, conocido por su historia y su cultura vibrante.', 4),
  ('Suecia', 'País en Europa del Norte, conocido por su diseño, su naturaleza y su calidad de vida.', 4),
  ('Suiza', 'País en Europa, conocido por sus Alpes, su relojería y su neutralidad política.', 4),
  ('Ucrania', 'País en Europa, conocido por su historia y sus llanuras fértiles.', 4),
  ('Vaticano', 'Pequeño país en Europa, conocido por ser la sede de la Iglesia Católica y sus obras de arte.', 4),

  ('Australia', 'País insular en Oceanía, conocido por su vida salvaje única y sus vastos paisajes.', 5),
  ('Fiyi', 'País insular en Oceanía, conocido por sus playas paradisíacas y su cultura melanesia.', 5),
  ('Islas Marshall', 'País insular en Oceanía, conocido por su belleza natural y sus arrecifes de coral.', 5),
  ('Islas Salomón', 'País insular en Oceanía, conocido por sus playas tropicales y su biodiversidad.', 5),
  ('Kiribati', 'País insular en Oceanía, conocido por ser uno de los lugares más remotos del mundo.', 5),
  ('Micronesia', 'País insular en Oceanía, conocido por sus islas dispersas y sus arrecifes de coral.', 5),
  ('Nauru', 'País insular en Oceanía, conocido por ser uno de los países más pequeños del mundo.', 5),
  ('Nueva Zelanda', 'País insular en Oceanía, conocido por sus paisajes impresionantes y su cultura maorí.', 5),
  ('Palaos', 'País insular en Oceanía, conocido por sus aguas cristalinas y su rica vida marina.', 5),
  ('Papúa Nueva Guinea', 'País en Oceanía, conocido por su diversidad cultural y su biodiversidad.', 5),
  ('Samoa', 'País insular en Oceanía, conocido por su cultura polinesia y sus paisajes exuberantes.', 5),
  ('Tonga', 'País insular en Oceanía, conocido por sus playas de arena blanca y su cultura única.', 5),
  ('Tuvalu', 'País insular en Oceanía, conocido por su vulnerabilidad al cambio climático.', 5),
  ('Vanuatu', 'País insular en Oceanía, conocido por sus volcanes activos y su cultura vibrante.', 5);

INSERT INTO CIUDAD (nombre, descripcion, id_pais) VALUES
  ('Luanda', 'Capital de Angola, conocida por su puerto y su diversidad cultural.', 1),
  ('Argel', 'Capital de Argelia, conocida por su arquitectura colonial y su historia.', 2),
  ('Porto-Novo', 'Capital de Benín, conocida por su arquitectura colonial y su mercado.', 3),
  ('Gaborone', 'Capital de Botsuana, conocida por sus parques naturales y su economía estable.', 4),
  ('Uagadugú', 'Capital de Burkina Faso, conocida por su mercado y su arquitectura moderna.', 5),
  ('Buyumbura', 'Capital de Burundi, conocida por su mercado central y su lago.', 6),
  ('Praia', 'Capital de Cabo Verde, conocida por sus playas y su música tradicional.', 7),
  ('Yaundé', 'Capital de Camerún, conocida por su diversidad étnica y sus mercados.', 8),
  ('Yamena', 'Capital de Chad, conocida por su arquitectura colonial y su mercado central.', 9),
  ('Moroni', 'Capital de Comoras, conocida por su mezquita y su mercado de pescado.', 10),
  ('Brazzaville', 'Capital de Congo, conocida por su arquitectura colonial y su río.', 11),
  ('Yamusukro', 'Capital de Costa de Marfil, conocida por su basílica y su arquitectura moderna.', 12),
  ('El Cairo', 'Capital de Egipto, conocida por sus pirámides y su museo de antigüedades.', 13),
  ('Asmara', 'Capital de Eritrea, conocida por su arquitectura italiana y su clima fresco.', 14),
  ('Adís Abeba', 'Capital de Etiopía, conocida por sus iglesias talladas en roca y su historia.', 15),
  ('Libreville', 'Capital de Gabón, conocida por su arquitectura colonial y sus playas.', 16),
  ('Banjul', 'Capital de Gambia, conocida por su mercado y su arquitectura colonial.', 17),
  ('Acra', 'Capital de Ghana, conocida por su mercado de Makola y su fuerte histórico.', 18),
  ('Conakry', 'Capital de Guinea, conocida por su arquitectura colonial y su puerto.', 19),
  ('Bisáu', 'Capital de Guinea-Bisáu, conocida por su arquitectura colonial y su mercado.', 20),
  ('Malabo', 'Capital de Guinea Ecuatorial, conocida por su arquitectura colonial y su clima tropical.', 21),
  ('Nairobi', 'Capital de Kenia, conocida por su parque nacional y su vida nocturna.', 22),
  ('Maseru', 'Capital de Lesoto, conocida por su clima templado y sus montañas.', 23),
  ('Monrovia', 'Capital de Liberia, conocida por sus playas y su historia colonial.', 24),
  ('Trípoli', 'Capital de Libia, conocida por sus ruinas antiguas y su medina.', 25),
  ('Antananarivo', 'Capital de Madagascar, conocida por su arquitectura colonial y su mercado.', 26),
  ('Lilongüe', 'Capital de Malaui, conocida por su mercado central y su arquitectura colonial.', 27),
  ('Bamako', 'Capital de Malí, conocida por su mezquita y su historia imperial.', 28),
  ('Rabat', 'Capital de Marruecos, conocida por su medina y su arquitectura islámica.', 29),
  ('Port Louis', 'Capital de Mauricio, conocida por sus playas y su mezcla cultural.', 30),
  ('Nuakchot', 'Capital de Mauritania, conocida por su mezquita y su mercado.', 31),
  ('Maputo', 'Capital de Mozambique, conocida por sus playas y su arquitectura colonial.', 32),
  ('Windhoek', 'Capital de Namibia, conocida por su arquitectura colonial alemana y su cerveza.', 33),
  ('Niamey', 'Capital de Níger, conocida por su arquitectura colonial y su mercado.', 34),
  ('Abuya', 'Capital de Nigeria, conocida por su mercado y su vida nocturna.', 35),
  ('Bangui', 'Capital de República Centroafricana, conocida por su mercado y su arquitectura colonial.', 36),
  ('Kinshasa', 'Capital de República Democrática del Congo, conocida por su vida nocturna y su río.', 37),
  ('Kigali', 'Capital de Ruanda, conocida por su arquitectura moderna y su mercado.', 38),
  ('Santo Tomé', 'Capital de Santo Tomé y Príncipe, conocida por sus playas y su arquitectura colonial.', 39),
  ('Dakar', 'Capital de Senegal, conocida por su mercado y su vida nocturna.', 40),
  ('Victoria', 'Capital de Seychelles, conocida por sus playas y su belleza natural.', 41),
  ('Freetown', 'Capital de Sierra Leona, conocida por su historia colonial y su mercado.', 42),
  ('Mogadiscio', 'Capital de Somalia, conocida por su arquitectura colonial y su puerto.', 43),
  ('Mbabane', 'Capital de Suazilandia, conocida por su mercado y su clima templado.', 44),
  ('Pretoria', 'Administrativa de Sudáfrica, conocida por sus jardines y su arquitectura colonial.', 45),
  ('Jartum', 'Capital de Sudán, conocida por su mezquita y su arquitectura islámica.', 46),
  ('Yuba', 'Capital de Sudán del Sur, conocida por su arquitectura moderna y su río.', 47),
  ('Dodoma', 'Capital de Tanzania, conocida por su arquitectura colonial y su mercado.', 48),
  ('Lomé', 'Capital de Togo, conocida por su arquitectura colonial y su mercado central.', 49),
  ('Túnez', 'Capital de Túnez, conocida por su medina y su arquitectura islámica.', 50),
  ('Kampala', 'Capital de Uganda, conocida por su mercado y su vida nocturna.', 51),
  ('Yibuti', 'Capital de Yibuti, conocida por su puerto estratégico y su mercado.', 52),
  ('Lusaka', 'Capital de Zambia, conocida por su mercado y su arquitectura colonial.', 53),
  ('Harare', 'Capital de Zimbabue, conocida por sus museos y su arquitectura colonial.', 54),

  ('Washington D.C.', 'Capital de Estados Unidos, conocida por sus monumentos y museos.', 55),
  ('Ottawa', 'Capital de Canadá, conocida por sus parques y su calidad de vida.', 56),
  ('Ciudad de México', 'Capital de México, conocida por su historia colonial y su comida.', 57),
  ('La Habana', 'Capital de Cuba, conocida por su arquitectura colonial y su música.', 58),
  ('Ciudad de Guatemala', 'Capital de Guatemala, conocida por su arquitectura colonial y su mercado.', 59),
  ('San José', 'Capital de Costa Rica, conocida por su biodiversidad y su clima templado.', 60),
  ('Ciudad de Panamá', 'Capital de Panamá, conocida por el Canal de Panamá y su skyline.', 61),
  ('Santo Domingo', 'Capital de República Dominicana, conocida por su historia colonial y su música.', 62),
  ('Tegucigalpa', 'Capital de Honduras, conocida por sus mercados y su arquitectura colonial.', 63),
  ('San Salvador', 'Capital de El Salvador, conocida por sus volcanes y su cultura.', 64),
  ('Brasilia', 'Capital de Brasil, conocida por su arquitectura moderna y su diversidad cultural.', 65),
  ('Buenos Aires', 'Capital de Argentina, conocida por su arquitectura y su vida nocturna.', 66),
  ('Bogotá', 'Capital de Colombia, conocida por su diversidad cultural y su vida nocturna.', 67),
  ('Lima', 'Capital de Perú, conocida por su gastronomía y sus ruinas incas.', 68),
  ('Caracas', 'Capital de Venezuela, conocida por su arquitectura y sus montañas.', 69),
  ('Santiago', 'Capital de Chile, conocida por sus parques y su cultura.', 70),
  ('Quito', 'Capital de Ecuador, conocida por su arquitectura colonial y su biodiversidad.', 71),
  ('La Paz', 'Capital de Bolivia, conocida por su altitud y su cultura indígena.', 72),
  ('Asunción', 'Capital de Paraguay, conocida por su río y su arquitectura.', 73),
  ('Montevideo', 'Capital de Uruguay, conocida por su costa y su arquitectura colonial.', 74),
  ('Managua', 'Capital de Nicaragua, conocida por sus lagos y volcanes.', 75),
  ('Belmopán', 'Capital de Belice, conocida por su biodiversidad y sus ruinas mayas.', 76),
  ('Kingston', 'Capital de Jamaica, conocida por su música y su historia.', 77),
  ('Puerto Príncipe', 'Capital de Haití, conocida por su historia colonial y su música.', 78),
  ('Puerto España', 'Capital de Trinidad y Tobago, conocida por su diversidad étnica y su carnaval.', 79),
  ('Bridgetown', 'Capital de Barbados, conocida por sus playas y su arquitectura colonial.', 80),
  ('Nasáu', 'Capital de Bahamas, conocida por sus playas y su turismo.', 81),
  ('Georgetown', 'Capital de Guyana, conocida por su arquitectura colonial y su selva.', 82),
  ('Paramaribo', 'Capital de Surinam, conocida por su arquitectura colonial y sus parques.', 83),
  ('Saint John', 'Capital de Antigua y Barbuda, conocida por sus playas y su historia colonial.', 84),
  ('Basseterre', 'Capital de San Cristóbal y Nieves, conocida por sus playas y su historia colonial.', 85),
  ('Castries', 'Capital de Santa Lucía, conocida por sus montañas y sus playas.', 86),
  ('Kingstown', 'Capital de San Vicente y las Granadinas, conocida por sus islas paradisíacas y su cultura.', 87),
  ('Saint George', 'Capital de Granada, conocida por su belleza natural y su historia colonial.', 88),
  ('Roseau', 'Capital de Dominica, conocida por sus montañas y su belleza natural.', 89),

  ('Pekín', 'Capital de China, conocida por su historia milenaria y su modernidad.', 90),
  ('Nueva Delhi', 'Capital de India, conocida por su diversidad cultural y sus monumentos históricos.', 91),
  ('Yakarta', 'Capital de Indonesia, conocida por su vida urbana y su rica cultura.', 92),
  ('Islamabad', 'Capital de Pakistán, conocida por sus monumentos históricos y su arquitectura.', 93),
  ('Daca', 'Capital de Bangladesh, conocida por su historia y su bulliciosa vida callejera.', 94),
  ('Tokio', 'Capital de Japón, conocida por su tecnología avanzada y su cultura tradicional.', 95),
  ('Manila', 'Capital de Filipinas, conocida por su rica historia y sus hermosas playas.', 96),
  ('Hanói', 'Capital de Vietnam, conocida por su historia colonial y su vibrante vida urbana.', 97),
  ('Teherán', 'Capital de Irán, conocida por su historia antigua y su arquitectura moderna.', 98),
  ('Ankara', 'Capital de Turquía, conocida por sus monumentos históricos y su vida urbana.', 99),
  ('Moscú', 'Capital de Rusia, conocida por su arquitectura y su importancia histórica.', 100),
  ('Seúl', 'Capital de Corea del Sur, conocida por su tecnología y su cultura pop.', 101),
  ('Riad', 'Capital de Arabia Saudita, conocida por su riqueza petrolera y su arquitectura moderna.', 102),
  ('Bagdad', 'Capital de Irak, conocida por su historia antigua y su importancia política.', 103),
  ('Kabul', 'Capital de Afganistán, conocida por su historia y sus desafíos políticos.', 104),
  ('Bangkok', 'Capital de Tailandia, conocida por su vida nocturna y sus templos budistas.', 105),
  ('Taipéi', 'Capital de Taiwán, conocida por su tecnología y su cultura.', 106),
  ('Colombo', 'Capital de Sri Lanka, conocida por sus playas y su patrimonio cultural.', 107),
  ('Kuala Lumpur', 'Capital de Malasia, conocida por sus rascacielos y su comida callejera.', 108),
  ('Singapur', 'Ciudad-estado de Singapur, conocida por su desarrollo económico y su limpieza.', 109),
  ('Tashkent', 'Capital de Uzbekistán, conocida por su historia y sus monumentos antiguos.', 110),
  ('Saná', 'Capital de Yemen, conocida por su arquitectura antigua y su historia.', 111),
  ('Katmandú', 'Capital de Nepal, conocida por su cultura y su proximidad al Himalaya.', 112),
  ('Damasco', 'Capital de Siria, conocida por su historia antigua y su mezcla de culturas.', 113),
  ('Nom Pen', 'Capital de Camboya, conocida por sus templos antiguos y su vida urbana.', 114),
  ('Mascate', 'Capital de Omán, conocida por su arquitectura y su riqueza petrolera.', 115),
  ('Doha', 'Capital de Qatar, conocida por su desarrollo urbano y su economía basada en el petróleo.', 116),
  ('Kuwait', 'Capital de Kuwait, conocida por su riqueza petrolera y su desarrollo económico.', 117),
  ('Beirut', 'Capital de Líbano, conocida por su historia y su mezcla de culturas.', 118),
  ('Jerusalén', 'Capital de Israel, reconocida por su significado religioso y sus disputas políticas.', 119),
  ('Ulán Bator', 'Capital de Mongolia, conocida por su historia nómada y su cultura.', 120),
  ('Amán', 'Capital de Jordania, conocida por su historia antigua y sus sitios arqueológicos.', 121),
  ('Abu Dabi', 'Capital de Emiratos Árabes Unidos, conocida por su desarrollo urbano y su riqueza petrolera.', 122),
  ('Vientián', 'Capital de Laos, conocida por su arquitectura colonial y su vida tranquila.', 123),
  ('Biskek', 'Capital de Kirguistán, conocida por su paisaje montañoso y sus lagos.', 124),
  ('Daca', 'Capital de Bangladés, conocida por su densa población y sus desafíos económicos.', 125),
  ('Bakú', 'Capital de Azerbaiyán, conocida por su mezcla de culturas y su arquitectura moderna.', 126),
  ('Manama', 'Capital de Bahréin, conocida por su economía basada en el petróleo y su arquitectura moderna.', 127),
  ('Timbu', 'Capital de Bután, conocida por su enfoque en la felicidad nacional bruta y su paisaje montañoso.', 128),
  ('Bandar Seri Begawan', 'Capital de Brunéi, conocida por su riqueza petrolera y su sistema político.', 129),
  ('Malé', 'Capital de Maldivas, conocida por sus playas y sus resorts de lujo.', 130),
  ('Dusambé', 'Capital de Tayikistán, conocida por su paisaje montañoso y sus antiguas rutas comerciales.', 131),
  ('Dili', 'Capital de Timor Oriental, conocida por su historia reciente de independencia y sus playas vírgenes.', 132),
  ('Asjabad', 'Capital de Turkmenistán, conocida por su régimen político autoritario y su vasta reserva de gas natural.', 133),

  ('Tirana', 'Capital de Albania, conocida por su mezcla de arquitectura y su vibrante vida urbana.', 134),
  ('Berlín', 'Capital de Alemania, conocida por su historia, su arte y su vida nocturna.', 135),
  ('Andorra la Vieja', 'Capital de Andorra, conocida por sus estaciones de esquí y su encanto medieval.', 136),
  ('Viena', 'Capital de Austria, conocida por su arte, su música y su arquitectura barroca.', 137),
  ('Bruselas', 'Capital de Bélgica, conocida por su chocolate, su cerveza y su sede de la Unión Europea.', 138),
  ('Minsk', 'Capital de Bielorrusia, conocida por su arquitectura soviética y sus parques.', 139),
  ('Sarajevo', 'Capital de Bosnia y Herzegovina, conocida por su historia y su mezcla cultural.', 140),
  ('Sofía', 'Capital de Bulgaria, conocida por su historia y sus iglesias ortodoxas.', 141),
  ('Nicosia', 'Capital de Chipre, conocida por su historia antigua y su mezcla de culturas.', 142),
  ('Zagreb', 'Capital de Croacia, conocida por su arquitectura histórica y su calidad de vida.', 143),
  ('Copenhague', 'Capital de Dinamarca, conocida por su diseño, su gastronomía y su estilo de vida.', 144),
  ('Bratislava', 'Capital de Eslovaquia, conocida por su casco antiguo y su río Danubio.', 145),
  ('Liubliana', 'Capital de Eslovenia, conocida por su arquitectura barroca y su ambiente relajado.', 146),
  ('Madrid', 'Capital de España, conocida por su historia, su arte y su vida nocturna.', 147),
  ('Tallin', 'Capital de Estonia, conocida por su tecnología y su bien conservado casco antiguo.', 148),
  ('Helsinki', 'Capital de Finlandia, conocida por su diseño, su sauna y su calidad de vida.', 149),
  ('París', 'Capital de Francia, conocida por su arte, su moda y su cocina.', 150),
  ('Atenas', 'Capital de Grecia, conocida por su historia antigua, sus ruinas y su gastronomía.', 151),
  ('Budapest', 'Capital de Hungría, conocida por sus baños termales y su arquitectura.', 152),
  ('Dublín', 'Capital de Irlanda, conocida por sus pubs, su música y su ambiente acogedor.', 153),
  ('Reikiavik', 'Capital de Islandia, conocida por su geotermia y sus auroras boreales.', 154),
  ('Roma', 'Capital de Italia, conocida por su historia, su arte y su gastronomía.', 155),
  ('Riga', 'Capital de Letonia, conocida por su arquitectura Art Nouveau y su historia.', 156),
  ('Vaduz', 'Capital de Liechtenstein, conocida por su tamaño diminuto y su centro histórico.', 157),
  ('Vilna', 'Capital de Lituania, conocida por su arquitectura barroca y su historia.', 158),
  ('Luxemburgo', 'Capital de Luxemburgo, conocida por su papel financiero y su historia medieval.', 159),
  ('La Valeta', 'Capital de Malta, conocida por su historia y su arquitectura barroca.', 160),
  ('Chisináu', 'Capital de Moldavia, conocida por sus parques y sus monumentos soviéticos.', 161),
  ('Mónaco', 'Capital de Mónaco, conocida por su lujo, su puerto y su famoso casino.', 162),
  ('Podgorica', 'Capital de Montenegro, conocida por sus iglesias ortodoxas y su costa.', 163),
  ('Oslo', 'Capital de Noruega, conocida por su fiordos, su calidad de vida y su arte.', 164),
  ('Ámsterdam', 'Capital de los Países Bajos, conocida por sus canales y su cultura liberal.', 165),
  ('Varsovia', 'Capital de Polonia, conocida por su reconstrucción tras la Segunda Guerra Mundial y su historia.', 166),
  ('Lisboa', 'Capital de Portugal, conocida por su historia marítima, su fado y su comida.', 167),
  ('Londres', 'Capital del Reino Unido, conocida por su historia, su cultura y sus mercados.', 168),
  ('Praga', 'Capital de la República Checa, conocida por su casco antiguo y su cerveza.', 169),
  ('Bucarest', 'Capital de Rumania, conocida por su arquitectura Art Nouveau y su historia.', 170),
  ('San Marino', 'Capital de San Marino, conocida por su pequeño tamaño y su arquitectura medieval.', 171),
  ('Belgrado', 'Capital de Serbia, conocida por su historia y su animada vida nocturna.', 172),
  ('Estocolmo', 'Capital de Suecia, conocida por su diseño, sus museos y su estilo de vida.', 173),
  ('Berna', 'Capital de Suiza, conocida por sus Alpes, su relojería y su neutralidad política.', 174),
  ('Kiev', 'Capital de Ucrania, conocida por su historia, sus iglesias ortodoxas y sus parques.', 175),
  ('Ciudad del Vaticano', 'Capital del Vaticano, conocida por ser la sede del Papa y sus obras de arte.', 176),

  ('Suva', 'Capital de Fiyi, conocida por su ambiente tropical y su vida nocturna.', 177),
  ('Majuro', 'Capital de las Islas Marshall, conocida por sus arrecifes de coral y sus aguas cristalinas.', 178),
  ('Honiara', 'Capital de las Islas Salomón, conocida por sus playas y su historia de la Segunda Guerra Mundial.', 179),
  ('Tarawa', 'Capital de Kiribati, conocida por su belleza natural y su importancia estratégica.', 180),
  ('Palikir', 'Capital de Micronesia, conocida por sus islas vírgenes y su vida marina.', 181),
  ('Yaren', 'Capital de Nauru, conocida por su pequeño tamaño y su ambiente tranquilo.', 182),
  ('Wellington', 'Capital de Nueva Zelanda, conocida por su cultura artística y sus paisajes.', 183),
  ('Melekeok', 'Capital de Palaos, conocida por sus arrecifes de coral y su ecoturismo.', 184),
  ('Puerto Moresby', 'Capital de Papúa Nueva Guinea, conocida por su diversidad cultural y su mercado de arte.', 185),
  ('Apia', 'Capital de Samoa, conocida por su cultura polinesia y sus playas de arena blanca.', 186),
  ('Nukualofa', 'Capital de Tonga, conocida por su ambiente relajado y su herencia polinesia.', 187),
  ('Funafuti', 'Capital de Tuvalu, conocida por su vulnerabilidad al cambio climático y sus playas.', 188),
  ('Port Vila', 'Capital de Vanuatu, conocida por sus volcanes y su cultura autóctona.', 189);

INSERT INTO EMPRESA (nombre, descripcion) VALUES
  ('Warner Bros. Pictures', 'Warner Bros. Pictures es una de las principales productoras y distribuidoras de cine del mundo. Conocida por producir una amplia variedad de películas, desde grandes éxitos de taquilla hasta películas aclamadas por la crítica.'),
  ('Walt Disney Pictures', 'Walt Disney Pictures es conocida por producir películas familiares y animadas, así como también por sus franquicias icónicas como Marvel y Star Wars.'),
  ('Universal Pictures', 'Universal Pictures es una de las productoras de cine más antiguas de Hollywood. Conocida por sus películas de géneros variados, incluyendo acción, comedia, terror y más.'),
  ('Netflix', 'Netflix es una plataforma de streaming que produce y distribuye una amplia gama de series y películas originales. Ha ganado reconocimiento por sus producciones innovadoras y su capacidad para llegar a audiencias globales.'),
  ('HBO', 'HBO es conocida por producir series de alta calidad, muchas de las cuales han sido aclamadas por la crítica y han ganado numerosos premios. Además de sus series originales, también produce películas y documentales.'),
  ('Paramount Pictures', 'Paramount Pictures es una de las principales productoras de cine de Hollywood, conocida por producir películas de gran presupuesto y franquicias exitosas.'),
  ('Sony Pictures Entertainment', 'Sony Pictures Entertainment es una empresa de entretenimiento que produce y distribuye una amplia variedad de contenido, incluyendo películas, series de televisión y programas de entretenimiento.'),
  ('20th Century Studios', 'Anteriormente conocida como 20th Century Fox, esta empresa es conocida por producir una amplia variedad de películas, incluyendo grandes éxitos de taquilla y películas de culto.'),
  ('Lionsgate', 'Lionsgate es una productora y distribuidora de películas conocida por sus producciones independientes y películas de género, así como también por la franquicia de Los Juegos del Hambre.'),
  ('Amazon Studios', 'Amazon Studios es la división de producción de Amazon, conocida por producir y distribuir series y películas originales para su plataforma de streaming, Amazon Prime Video.'),
  ('Marvel Studios', 'Marvel Studios es conocida por producir películas basadas en los populares personajes de Marvel Comics, incluyendo películas del Universo Cinematográfico de Marvel (MCU). Ha sido fundamental en la creación de franquicias exitosas y películas de superhéroes.'),
  ('DreamWorks Animation', 'DreamWorks Animation es conocida por producir películas animadas de gran éxito, como Shrek, Madagascar y Kung Fu Panda.'),
  ('Pixar Animation Studios', 'Pixar es una empresa de animación conocida por crear películas animadas innovadoras y emocionalmente impactantes, como Toy Story, Buscando a Nemo y Los Increíbles.'),
  ('A24', 'A24 es una empresa de entretenimiento conocida por producir películas independientes aclamadas por la crítica, como Moonlight, Lady Bird y Hereditary.'),
  ('Focus Features', 'Focus Features es una división de Universal Pictures que se especializa en la producción y distribución de películas independientes y de autor.'),
  ('New Line Cinema', 'New Line Cinema es una productora de cine conocida por producir películas de géneros variados, incluyendo terror, comedia y acción.'),
  ('Studio Ghibli', 'Studio Ghibli es un estudio de animación japonés conocido por crear películas animadas de gran calidad artística y narrativa, como Mi Vecino Totoro, El Viaje de Chihiro y La Princesa Mononoke.'),
  ('Legendary Entertainment', 'Legendary Entertainment es una empresa de medios conocida por producir películas de gran presupuesto y franquicias populares, como Jurassic World y Godzilla.'),
  ('Amblin Entertainment', 'Amblin Entertainment es una productora de cine fundada por Steven Spielberg, conocida por producir películas familiares y de aventuras, así como también por sus colaboraciones con otros cineastas.'),
  ('Blumhouse Productions', 'Blumhouse Productions es una empresa de producción de películas de terror y thriller conocida por producir películas de bajo presupuesto que a menudo se convierten en éxitos de taquilla, como Paranormal Activity, La Purga y ¡Huye!.');

INSERT INTO GENERO (nombre, descripcion) VALUES
  ('Acción', 'Películas o series que se caracterizan por escenas llenas de energía, con combates, persecuciones y situaciones de alta tensión.'),
  ('Aventura', 'Historias emocionantes que suelen implicar viajes, descubrimientos y desafíos en entornos exóticos o fantásticos.'),
  ('Comedia', 'Producciones destinadas a hacer reír al público, con situaciones divertidas, humor físico o diálogos ingeniosos.'),
  ('Drama', 'Películas o series que se centran en conflictos emocionales y personales, explorando temas profundos y conmovedores.'),
  ('Ciencia ficción', 'Historias que presentan avances tecnológicos, futuros alternativos o viajes espaciales, explorando posibilidades más allá de la realidad actual.'),
  ('Fantasía', 'Mundos imaginarios, criaturas mágicas y poderes sobrenaturales son características comunes de este género.'),
  ('Terror', 'Películas o series diseñadas para asustar y provocar miedo en el público, a menudo con elementos de suspenso, monstruos y situaciones escalofriantes.'),
  ('Suspense', 'Historias llenas de intriga y tensión, manteniendo al público en vilo sobre lo que sucederá a continuación.'),
  ('Romance', 'Historias de amor y relaciones personales, con énfasis en los aspectos emocionales y románticos de los personajes.'),
  ('Animación', 'Producciones en las que los personajes y entornos son creados mediante animación, ya sea tradicional o por computadora.'),
  ('Documental', 'Películas o series que presentan hechos reales, personas reales y eventos históricos, con el objetivo de informar, educar o concientizar al público.'),
  ('Musical', 'Historias en las que la música y el baile desempeñan un papel importante en la narrativa, a menudo con números musicales integrados en la trama.'),
  ('Western', 'Historias ambientadas en el viejo oeste americano, con tiroteos, duelos y paisajes desérticos como elementos característicos.'),
  ('Crimen', 'Películas o series que se centran en la comisión y resolución de crímenes, a menudo con detectives, policías y criminales como protagonistas.'),
  ('Misterio', 'Historias que giran en torno a la resolución de un enigma o la búsqueda de la verdad, manteniendo al público intrigado hasta el final.');

INSERT INTO PREMIO (nombre, descripcion, categoria) VALUES
  ('Oscar', 'Los premios de la Academia de las Artes y las Ciencias Cinematográficas, otorgados anualmente por logros destacados en la industria cinematográfica.', 'Cine'),
  ('Emmy', 'Premios otorgados por la Academia de Artes y Ciencias de la Televisión para reconocer la excelencia en la industria de la televisión estadounidense.', 'Televisión'),
  ('Globo de Oro', 'Premios otorgados por la Asociación de Prensa Extranjera de Hollywood, que reconoce la excelencia en cine y televisión.', 'Cine, Televisión'),
  ('BAFTA', 'Premios de la Academia Británica de las Artes Cinematográficas y de la Televisión, que reconoce la excelencia en cine, televisión y videojuegos.', 'Cine, Televisión, Videojuegos'),
  ('Cannes Film Festival', 'Uno de los festivales de cine más prestigiosos del mundo, celebrado anualmente en Cannes, Francia.', 'Cine'),
  ('Festival de Sundance', 'Festival de cine independiente que se celebra anualmente en Utah, Estados Unidos, considerado como una plataforma importante para cineastas emergentes.', 'Cine'),
  ('Premios Tony', 'Premios otorgados por la Liga de Teatros Americanos y Productores, que reconoce la excelencia en producciones teatrales de Broadway.', 'Teatro'),
  ('Festival de Venecia', 'Uno de los festivales de cine más antiguos y prestigiosos del mundo, celebrado anualmente en Venecia, Italia.', 'Cine'),
  ('Premios MTV', 'Premios otorgados por MTV para reconocer logros en música, cine y televisión, con énfasis en la cultura juvenil.', 'Música, Cine, Televisión');

INSERT INTO RESTRICCION (nombre, descripcion, tipo_restriccion) VALUES
  ('Apta para todo público (ATP)', 'La película o serie es apta para todo público. No contiene contenido que pueda considerarse inapropiado para niños.', 'ATP'),
  ('Todo público (TP)', 'La película o serie es apta para todo público. No contiene contenido que pueda considerarse inapropiado para niños.', 'TP'),
  ('Clasificación por edades', 'La clasificación de películas establecida por la MPAA. Incluye categorías como G, PG, PG-13, R y NC-17.', 'MPAA'),
  ('Parental Guidance', 'La película o serie puede contener contenido inapropiado para niños menores de 15 años. Se recomienda la supervisión de un adulto.', 'PG-15'),
  ('Restricted', 'La película o serie contiene contenido para adultos. No se recomienda para menores de 17 años sin la compañía de un adulto.', 'R-Rated');
