CREATE DATABASE muchocine;

USE muchocine;

CREATE TABLE IDIOMA (
    codigo_iso CHAR(2) NOT NULL PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL
);

CREATE TABLE INFORMACION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL
);

CREATE TABLE PAIS (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    continente ENUM('AFRICA', 'AMERICA', 'ASIA', 'EUROPA', 'OCEANIA') NOT NULL
);

CREATE TABLE PAQUETE (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('personal', 'duo', 'familiar') NOT NULL,
    periodo ENUM('mensual', 'semestral', 'anual')
);

CREATE TABLE PERIODO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    CHECK (fecha_inicio <= fecha_fin)
);

CREATE TABLE CIUDAD (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(20) NOT NULL,
    id_pais INT NOT NULL,
    FOREIGN KEY (id_pais) REFERENCES PAIS(id)
);

CREATE TABLE EMPRESA (
    id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES INFORMACION(id)
);

CREATE TABLE GENERO (
    id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES INFORMACION(id)
);

CREATE TABLE OFERTA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    precio DECIMAL(3, 2) NOT NULL,
    descuento DECIMAL(3, 2),
    id_periodo INT NOT NULL,
    FOREIGN KEY (id_periodo) REFERENCES PERIODO(id)
);

CREATE TABLE PREMIO (
    id INT NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES INFORMACION(id)
);

CREATE TABLE RESTRICCION (
    id INT NOT NULL,
    categoria ENUM('ATP', 'TP', 'MPAA', 'PG-15', 'R-Rated'),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES INFORMACION(id)
);


CREATE TABLE PERSONA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    apellido_paterno VARCHAR(20),
    apellido_materno VARCHAR(20),
    fecha_nacimiento DATE NOT NULL,
    id_residencia INT NOT NULL,
    sexo ENUM('F', 'M', 'N'),
    FOREIGN KEY (id_residencia) REFERENCES CIUDAD(id)
);

CREATE TABLE ACTOR (
    id INT NOT NULL,
    id_origen INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSONA(id),
    FOREIGN KEY (id_origen) REFERENCES CIUDAD(id)
);

CREATE TABLE CUENTA (
    id INT NOT NULL,
    correo VARCHAR(255) NOT NULL UNIQUE,
    usuario VARCHAR(255) NOT NULL UNIQUE,
    clave VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES PERSONA(id)
);

CREATE TABLE SUBCUENTA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_cuenta INT NOT NULL,
    FOREIGN KEY (id_cuenta) REFERENCES CUENTA(id)
);

CREATE TABLE SUSCRIPCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    forma_pago ENUM('debito', 'credito') NOT NULL,
    duracion DECIMAL(6, 2) NOT NULL,
    id_cuenta INT NOT NULL,
    id_periodo INT NOT NULL,
    FOREIGN KEY (id_cuenta) REFERENCES CUENTA(id),
    FOREIGN KEY (id_periodo) REFERENCES PERIODO(id)
);

CREATE TABLE TRANSACCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    monto DECIMAL(3, 2) NOT NULL,
    id_suscripcion INT NOT NULL,
    FOREIGN KEY (id_suscripcion) REFERENCES SUSCRIPCION(id)
);


CREATE TABLE VIDEO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    duracion DECIMAL(10, 2) NOT NULL,
    estreno YEAR NOT NULL,
    link_portada VARCHAR(255) NOT NULL,
    id_restriccion INT NOT NULL,
    FOREIGN KEY (id_restriccion) REFERENCES RESTRICCION(id)
);

CREATE TABLE AUDIO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link_audio VARCHAR(255) NOT NULL,
    codigo_idioma CHAR(2) NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (codigo_idioma) REFERENCES IDIOMA(codigo_iso),
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);

CREATE TABLE REPRODUCCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_cuenta INT NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (id_cuenta) REFERENCES CUENTA(id),
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);

CREATE TABLE SUBTITULO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link_subtitulo VARCHAR(255) NOT NULL,
    codigo_idioma CHAR(2) NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (codigo_idioma) REFERENCES IDIOMA(codigo_iso),
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);

CREATE TABLE TRAILER (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link_video VARCHAR(255) NOT NULL,
    duracion DECIMAL(5, 2) NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);

CREATE TABLE PELICULA (
    id INT NOT NULL,
    link_video VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES VIDEO(id)
);

CREATE TABLE SERIE (
    id INT NOT NULL,
    cantidad_temporadas INT,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES VIDEO(id)
);

CREATE TABLE TEMPORADA (
    id INT NOT NULL,
    id_serie INT NOT NULL,
    cantidad_capitulos INT,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES INFORMACION(id),
    FOREIGN KEY (id_serie) REFERENCES SERIE(id)
);

CREATE TABLE CAPITULO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link_video VARCHAR(255) NOT NULL UNIQUE,
    duracion DECIMAL(10, 2),
    id_temporada INT NOT NULL,
    FOREIGN KEY (id_temporada) REFERENCES TEMPORADA(id)
);

CREATE TABLE ESTRENO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL,
    tipo ENUM('pelicula', 'serie') NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);


CREATE TABLE R_ACTOR_VIDEO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre_artistico VARCHAR(100) NOT NULL,
    rol ENUM('principal', 'secundario', 'reparto', 'extra', 'cameo') NOT NULL,
    id_actor INT NOT NULL,
    id_video INT NOT NULL,
    FOREIGN KEY (id_actor) REFERENCES ACTOR(id),
    FOREIGN KEY (id_video) REFERENCES VIDEO(id)
);

CREATE TABLE R_VIDEO_PREMIO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha YEAR NOT NULL,
    tipo ENUM('pelicula', 'serie') NOT NULL,
    id_video INT NOT NULL,
    id_premio INT NOT NULL,
    FOREIGN KEY (id_video) REFERENCES VIDEO(id),
    FOREIGN KEY (id_premio) REFERENCES PREMIO(id)
);

CREATE TABLE R_VIDEO_GENERO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_video INT NOT NULL,
    id_genero INT NOT NULL,
    FOREIGN KEY (id_video) REFERENCES VIDEO(id),
    FOREIGN KEY (id_genero) REFERENCES GENERO(id)
);

CREATE TABLE R_SUBCUENTA_GENERO (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_subcuenta INT NOT NULL,
    id_genero INT NOT NULL,
    FOREIGN KEY (id_subcuenta) REFERENCES SUBCUENTA(id),
    FOREIGN KEY (id_genero) REFERENCES GENERO(id)
);

CREATE TABLE R_VIDEO_EMPRESA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    costo DECIMAL(10, 2) NOT NULL,
    id_video INT NOT NULL,
    id_empresa INT NOT NULL,
    FOREIGN KEY (id_video) REFERENCES VIDEO(id),
    FOREIGN KEY (id_empresa) REFERENCES EMPRESA(id)
);

CREATE TABLE R_OFERTA_SUSCRIPCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_oferta INT NOT NULL,
    id_suscripcion INT NOT NULL,
    FOREIGN KEY (id_oferta) REFERENCES OFERTA(id),
    FOREIGN KEY (id_suscripcion) REFERENCES SUSCRIPCION(id)
);

CREATE TABLE H_OFERTA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_oferta INT NOT NULL,
    id_nuevo_periodo INT NOT NULL,
    FOREIGN KEY (id_oferta) REFERENCES OFERTA(id),
    FOREIGN KEY (id_nuevo_periodo) REFERENCES PERIODO(id)
);

CREATE TABLE R_PAQUETE_SUSCRIPCION (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_paquete INT NOT NULL,
    id_suscripcion INT NOT NULL,
    FOREIGN KEY (id_paquete) REFERENCES PAQUETE(id),
    FOREIGN KEY (id_suscripcion) REFERENCES SUSCRIPCION(id)
);
