import herramientas.grafico.figuras.Figura;
import herramientas.grafico.figuras.Compuesto;
import herramientas.grafico.figuras.Rectangulo;
import herramientas.grafico.animaciones.Animacion;
import estDat.lineales.Cola;
import estDat.noLineales.ArbolBB;

import java.util.ArrayList;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class CrearSet extends JDialog {
    private DefaultTableModel modelo = new DefaultTableModel();
    private PanelAnimacion panelAnim = new PanelAnimacion();//mismo tamaño
    private Compuesto figura;
    private ArbolBB prioridades;
    private Cola<Integer> cola;

    public CrearSet() {
        prioridades = new ArbolBB();
        setModal(true);
        initComponents();
        String[]titulo= new String[]{"Figura","Posición","Dimensión", "Prioridad"};
        modelo.setColumnIdentifiers(titulo);
        tablaFiguras.setModel(modelo); 

        panelAnim.setSize(660,760);
        panelAnim.setLocation(0, 0);

        panelFiguras.removeAll();
        panelFiguras.add(panelAnim, BorderLayout.CENTER);
        panelFiguras.revalidate();
        panelFiguras.repaint();

        pack();
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        figura = new Compuesto(null, panelAnim, null);
        panelAnim.agregarFigura(figura);
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        back = new javax.swing.JPanel();
        headA = new javax.swing.JPanel();
        IcUserA = new javax.swing.JLabel();
        LogoA = new javax.swing.JLabel();
        /*botonInicio = new javax.swing.JPanel();
        IcHouseA = new javax.swing.JLabel();*/
        panelFiguras = new javax.swing.JPanel();
        setAnim = new javax.swing.JPanel();
        figuraLetra = new javax.swing.JLabel();
        listaFiguras = new javax.swing.JComboBox<>();
        pos = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        posX = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        y = new javax.swing.JLabel();
        posY = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador5 = new javax.swing.JSeparator();
        botAgregar = new javax.swing.JButton();
        botNuevo = new javax.swing.JButton();
        botMover = new javax.swing.JButton();
        separador4 = new javax.swing.JSeparator();
        botElimTodo = new javax.swing.JButton();
        botElim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFiguras = new javax.swing.JTable();
        guardarLetra = new javax.swing.JLabel();
        campoGuardar = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JPanel();
        guardarA = new javax.swing.JLabel();
        dimensionLetra = new javax.swing.JLabel();
        anchoLetra = new javax.swing.JLabel();
        altoLetra = new javax.swing.JLabel();
        campoAlto = new javax.swing.JTextField();
        campoAncho = new javax.swing.JTextField();
        botFondo = new javax.swing.JButton();
        prioridadLetra = new javax.swing.JLabel();
        campoPrior = new javax.swing.JTextField();
        separador6 = new javax.swing.JSeparator();
        botonVoz = new javax.swing.JButton();

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        back.setMinimumSize(new java.awt.Dimension(1000, 800));
        back.setPreferredSize(new java.awt.Dimension(1000, 800));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headA.setBackground(new java.awt.Color(0, 0, 0));
        headA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        headA.setPreferredSize(new java.awt.Dimension(1000, 52));

        IcUserA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/people.png"))); // NOI18N
        IcUserA.setText("jLabel2");
        IcUserA.setAlignmentY(0.0F);
        IcUserA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LogoA.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LogoA.setForeground(new java.awt.Color(255, 255, 255));
        LogoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.png"))); // NOI18N
        LogoA.setText("ANIMUSIC");

        /*botonInicio.setBackground(new java.awt.Color(0, 0, 0));
        botonInicio.setPreferredSize(new java.awt.Dimension(45, 32));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        botonInicioMouseClicked(evt);
        }
        });

        IcHouseA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IcHouseA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house2.png"))); // NOI18N
        IcHouseA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonInicioLayout = new javax.swing.GroupLayout(botonInicio);
        botonInicio.setLayout(botonInicioLayout);
        botonInicioLayout.setHorizontalGroup(
        botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(botonInicioLayout.createSequentialGroup()
        .addComponent(IcHouseA)
        .addGap(0, 10, Short.MAX_VALUE))
        );*/
        /*botonInicioLayout.setVerticalGroup(
        botonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(IcHouseA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );*/

        javax.swing.GroupLayout headALayout = new javax.swing.GroupLayout(headA);
        headA.setLayout(headALayout);
        headALayout.setHorizontalGroup(
            headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headALayout.createSequentialGroup()
                .addComponent(LogoA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 788, Short.MAX_VALUE)
                    /*.addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)*/
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IcUserA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        headALayout.setVerticalGroup(
            headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headALayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headALayout.createSequentialGroup()
                        .addGroup(headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                /*.addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)*/
                            .addComponent(IcUserA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        back.add(headA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        panelFiguras.setBackground(new java.awt.Color(65, 65, 67));
        panelFiguras.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelFigurasLayout = new javax.swing.GroupLayout(panelFiguras);
        panelFiguras.setLayout(panelFigurasLayout);
        panelFigurasLayout.setHorizontalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        panelFigurasLayout.setVerticalGroup(
            panelFigurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        back.add(panelFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 760));

        setAnim.setBackground(new java.awt.Color(65, 65, 67));
        setAnim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setAnim.setForeground(new java.awt.Color(255, 255, 255));

        figuraLetra.setBackground(new java.awt.Color(240, 235, 221));
        figuraLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        figuraLetra.setForeground(new java.awt.Color(255, 255, 255));
        figuraLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        figuraLetra.setText("FIGURA:");
        figuraLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaFiguras.setBackground(new java.awt.Color(240, 235, 221));
        listaFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".", "Acordeon", "Corno", "Electrica", "Flauta", "Guitarra", "Mandolina", "Maracas", "Microfono", "Platillos", "Saxofon", "Tambor", "Teclado", "Trompeta", "Tuba", "Violin", "Xilofono" }));
        listaFiguras.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    listaFigurasActionPerformed(evt);
                }
            });

        pos.setBackground(new java.awt.Color(240, 235, 221));
        pos.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pos.setForeground(new java.awt.Color(255, 255, 255));
        pos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos.setText("POSICIÓN:");
        pos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x.setBackground(new java.awt.Color(240, 235, 221));
        x.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setText("X:");
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        posX.setBackground(new java.awt.Color(65, 65, 67));
        posX.setForeground(new java.awt.Color(204, 204, 204));
        posX.setBorder(null);
        posX.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }

                public void keyReleased(KeyEvent e){}

                public void keyPressed(KeyEvent e){}
            });

        separador1.setBackground(new java.awt.Color(204, 204, 204));

        y.setBackground(new java.awt.Color(240, 235, 221));
        y.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        y.setForeground(new java.awt.Color(255, 255, 255));
        y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        y.setText("Y:");
        y.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        posY.setBackground(new java.awt.Color(65, 65, 67));
        posY.setForeground(new java.awt.Color(204, 204, 204));
        posY.setBorder(null);
        posY.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }

                public void keyReleased(KeyEvent e){}

                public void keyPressed(KeyEvent e){}
            });

        separador2.setBackground(new java.awt.Color(204, 204, 204));

        botAgregar.setBackground(new java.awt.Color(203, 182, 163));
        botAgregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botAgregar.setText("Agregar");
        botAgregar.setBorder(null);
        botAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botAgregar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botAgregarActionPerformed(evt);
                }
            });

        botNuevo.setBackground(new java.awt.Color(203, 182, 163));
        botNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botNuevo.setText("Nuevo");
        botNuevo.setBorder(null);
        botNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botNuevoActionPerformed(evt);
                }
            });

        separador4.setBackground(new java.awt.Color(204, 204, 204));

        botElimTodo.setBackground(new java.awt.Color(203, 182, 163));
        botElimTodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botElimTodo.setText("Eliminar todo");
        botElimTodo.setBorder(null);
        botElimTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botElimTodo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botElimTodoActionPerformed(evt);
                }
            });

        botElim.setBackground(new java.awt.Color(203, 182, 163));
        botElim.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botElim.setText("Eliminar");
        botElim.setBorder(null);
        botElim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botElim.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botElimActionPerformed(evt);
                }
            });

        tablaFiguras.setBackground(new java.awt.Color(240, 235, 221));
        tablaFiguras.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaFiguras.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
        tablaFiguras.setGridColor(new java.awt.Color(255, 255, 255));
        tablaFiguras.setSelectionForeground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(tablaFiguras);

        guardarLetra.setBackground(new java.awt.Color(240, 235, 221));
        guardarLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        guardarLetra.setForeground(new java.awt.Color(255, 255, 255));
        guardarLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarLetra.setText("Guardar como:");
        guardarLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoGuardar.setBackground(new java.awt.Color(65, 65, 67));
        campoGuardar.setForeground(new java.awt.Color(204, 204, 204));
        campoGuardar.setText("Figura");
        campoGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    campoGuardarActionPerformed(evt);
                }
            });

        botonGuardar.setBackground(new java.awt.Color(211, 137, 124));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    botonGuardarMouseClicked(evt);
                }
            });

        guardarA.setBackground(new java.awt.Color(240, 235, 221));
        guardarA.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        guardarA.setForeground(new java.awt.Color(255, 255, 255));
        guardarA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarA.setText("GUARDAR");
        guardarA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonGuardarLayout = new javax.swing.GroupLayout(botonGuardar);
        botonGuardar.setLayout(botonGuardarLayout);
        botonGuardarLayout.setHorizontalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGuardarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(guardarA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        botonGuardarLayout.setVerticalGroup(
            botonGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botMover.setBackground(new java.awt.Color(203, 182, 163));
        botMover.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botMover.setText("Mover");
        botMover.setBorder(null);
        botMover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botMover.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botMoverActionPerformed(evt);
                }
            });

        dimensionLetra.setBackground(new java.awt.Color(240, 235, 221));
        dimensionLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        dimensionLetra.setForeground(new java.awt.Color(255, 255, 255));
        dimensionLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimensionLetra.setText("DIMENSIÓN");
        dimensionLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        anchoLetra.setBackground(new java.awt.Color(240, 235, 221));
        anchoLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        anchoLetra.setForeground(new java.awt.Color(255, 255, 255));
        anchoLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anchoLetra.setText("Ancho:");
        anchoLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoAncho.setBackground(new java.awt.Color(65, 65, 67));
        campoAncho.setForeground(new java.awt.Color(204, 204, 204));
        campoAncho.setBorder(null);
        campoAncho.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }

                public void keyReleased(KeyEvent e){}

                public void keyPressed(KeyEvent e){}
            });

        separador3.setBackground(new java.awt.Color(204, 204, 204));

        altoLetra.setBackground(new java.awt.Color(240, 235, 221));
        altoLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        altoLetra.setForeground(new java.awt.Color(255, 255, 255));
        altoLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altoLetra.setText("Alto:");
        altoLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoAlto.setBackground(new java.awt.Color(65, 65, 67));
        campoAlto.setForeground(new java.awt.Color(204, 204, 204));
        campoAlto.setBorder(null);
        campoAlto.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }

                public void keyReleased(KeyEvent e){}

                public void keyPressed(KeyEvent e){}
            });

        separador5.setBackground(new java.awt.Color(204, 204, 204));

        botFondo.setBackground(new java.awt.Color(203, 182, 163));
        botFondo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botFondo.setText("Fondo");
        botFondo.setBorder(null);
        botFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botFondo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botFondoActionPerformed(evt);
                }
            });

        prioridadLetra.setBackground(new java.awt.Color(240, 235, 221));
        prioridadLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        prioridadLetra.setForeground(new java.awt.Color(255, 255, 255));
        prioridadLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prioridadLetra.setText("PRIORIDAD:");
        prioridadLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        campoPrior.setBackground(new java.awt.Color(65, 65, 67));
        campoPrior.setForeground(new java.awt.Color(204, 204, 204));
        campoPrior.setBorder(null);
        campoPrior.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }

                public void keyReleased(KeyEvent e){}

                public void keyPressed(KeyEvent e){}
            });

        separador6.setBackground(new java.awt.Color(204, 204, 204));

        botonVoz.setBackground(new java.awt.Color(203, 182, 163));
        botonVoz.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonVoz.setText("ON VOZ");
        botonVoz.setBorder(null);
        botonVoz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setAnimLayout = new javax.swing.GroupLayout(setAnim);
        setAnim.setLayout(setAnimLayout);
        setAnimLayout.setHorizontalGroup(
            setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(guardarLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(campoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(botMover, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botElimTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botElim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(setAnimLayout.createSequentialGroup()
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(separador1)
                            .addComponent(posX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(separador2)
                            .addComponent(posY, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(botAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(botFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(botNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                                .addComponent(figuraLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(listaFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                                .addComponent(anchoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(separador3)
                                    .addComponent(campoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(altoLetra)
                                .addGap(18, 18, 18)
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(separador5)
                                    .addComponent(campoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(setAnimLayout.createSequentialGroup()
                                        .addComponent(prioridadLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(separador6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoPrior, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(pos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dimensionLetra))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        setAnimLayout.setVerticalGroup(
            setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(figuraLetra)
                    .addComponent(listaFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(dimensionLetra)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anchoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(setAnimLayout.createSequentialGroup()
                            .addComponent(campoAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(separador5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(setAnimLayout.createSequentialGroup()
                            .addComponent(campoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(pos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posX)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posY)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(prioridadLetra))
                    .addComponent(campoPrior, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botElim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botElimTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botMover, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarLetra)
                    .addComponent(campoGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        back.add(setAnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 340, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>               

    private void botonInicioMouseClicked(MouseEvent evt) {
        dispose();
        new Inicio().setVisible(true);
    }

    private void campoGuardarActionPerformed(MouseEvent evt) {
        if (campoGuardar.getText().equals("Figura")) {
            campoGuardar.setText("");
            campoGuardar.setForeground(java.awt.Color.white);
        }
    }

    private void botonGuardarMouseClicked(MouseEvent evt) {
        int n = figura.getComponentes().getLongitud();
        if (n == 0) {
            JOptionPane.showMessageDialog(null, "Figura compuesta vacia!", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = campoGuardar.getText();
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un nombre", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        Figura fondo = panelAnim.getFondo();

        figura.setNombre(nombre);
        if (fondo != null) {
            figura.setPosicion(fondo.getPosicion());
            figura.setDimension(fondo.getDimension());
        }

        Serializado.serializarFigura(figura);
        JOptionPane.showMessageDialog(null, "Figura Compuesta creada!", null, JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    private void botElimActionPerformed(ActionEvent evt) {
        int elim = tablaFiguras.getSelectedRow(), aux;

        if(elim>=0){
            aux = Integer.parseInt((String) tablaFiguras.getValueAt(elim, 3));
            prioridades.eliminar(aux);

            figura.eliminarFigura(elim);
            panelAnim.repaint();
            modelo.removeRow(elim);
        }else{
            JOptionPane.showMessageDialog(null, "No hay datos que eliminar", null, JOptionPane.WARNING_MESSAGE);
        }
    }

    private void botElimTodoActionPerformed(ActionEvent evt) {
        figura.eliminarTodo();
        prioridades.vaciar();

        int eliTotal = tablaFiguras.getRowCount();
        for(int i = eliTotal - 1; i >= 0; i--){
            modelo.removeRow(i);
        }

        panelAnim.repaint();
    }

    private void botNuevoActionPerformed(ActionEvent evt) {
        posX.setText("");
        posY.setText("");
        campoAncho.setText("");
        campoAlto.setText("");
    }

    private void botAgregarActionPerformed(ActionEvent evt) {
        String f = (String) listaFiguras.getSelectedItem();
        if (f.equals(".")) {
            JOptionPane.showMessageDialog(null, "Selecciona una figura", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (posX.getText().equals("") || posY.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la posicion", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (campoAncho.getText().equals("") || campoAlto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese la dimension", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (campoPrior.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la prioridad", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        Point posicion = getPosicion();
        Dimension dimension = getDimension();
        int prioridad = Integer.parseInt(campoPrior.getText());
        prioridades.insertar(prioridad);

        Figura fig = Utils.crearFigura(f, posicion);
        fig.setDimension(dimension);
        figura.agregarFigura(fig, prioridad);

        generarTabla();
    }

    private void generarTabla() {
        modelo.setRowCount(0);

        cola = prioridades.inOrden();
        String[] agregar = new String[4];
        for (Figura f : figura.getComponentes()) {
            agregar[0] = f.getNombre();
            agregar[1] = f.getPosicion().x + " - " + f.getPosicion().y;
            agregar[2] = f.getDimension().width + " - " + f.getDimension().height;
            agregar[3] = cola.decolar()+"";

            modelo.addRow(agregar);
        }
    }

    private void botMoverActionPerformed(ActionEvent evt) {
        int e = tablaFiguras.getSelectedRow();

        if(e < 0){
            JOptionPane.showMessageDialog(null, "Selecciones una figura", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (posX.getText().equals("") || posY.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la posicion", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        Point p = getPosicion();
        figura.getComponentes().acceder(e).mover(p);
        String s = "x: " + p.x + " - y: " + p.y;
        tablaFiguras.setValueAt(s, e, 1);
    }                                   

    private void listaFigurasActionPerformed(java.awt.event.ActionEvent evt) {
        String select = listaFiguras.getSelectedItem().toString();
        if (select.equals(".")) return;
        Figura f = Utils.crearFigura(select, null);
        Archivo.escribirEstadisticaFigura(f.getNombre());
    }   

    private void botFondoActionPerformed(java.awt.event.ActionEvent evt) {
        if (posX.getText().equals("") || posY.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese la posicion", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if( campoAncho.getText().equals("") || campoAlto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese la dimension", null, JOptionPane.WARNING_MESSAGE);
            return;
        }

        Point posicion = getPosicion();
        Dimension dimension = getDimension();
        Figura f = new Rectangulo(posicion, dimension, java.awt.Color.white, panelAnim);
        panelAnim.agregarFondo(f);
    }
    
    private void botonVozActionPerformed(java.awt.event.ActionEvent evt) {
        Utils.vozFiguras(listaFiguras);
    } 

    private Point getPosicion() {
        return Utils.crearPosicion(posX.getText(), posY.getText());
    }

    private Dimension getDimension() {
        return Utils.crearDimension(campoAncho.getText(), campoAlto.getText());
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CrearSet().setVisible(true);
                }
            });
    }

    // private javax.swing.JLabel IcHouseA;
    private javax.swing.JLabel IcUserA;
    private javax.swing.JLabel LogoA;
    private javax.swing.JPanel back;
    private javax.swing.JButton botAgregar;
    private javax.swing.JButton botElim;
    private javax.swing.JButton botElimTodo;
    private javax.swing.JButton botNuevo;
    private javax.swing.JPanel botonGuardar;
    private javax.swing.JButton botMover;
    private javax.swing.JButton botonVoz;
    // private javax.swing.JPanel botonInicio;

    private javax.swing.JTextField campoGuardar;
    private javax.swing.JLabel figuraLetra;
    private javax.swing.JLabel guardarA;
    private javax.swing.JLabel guardarLetra;
    private javax.swing.JPanel headA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaFiguras;
    private javax.swing.JPanel panelFiguras;
    private javax.swing.JLabel pos;
    private javax.swing.JTextField posX;
    private javax.swing.JTextField posY;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JPanel setAnim;
    private javax.swing.JTable tablaFiguras;
    private javax.swing.JLabel x;
    private javax.swing.JLabel y;
    private javax.swing.JLabel dimensionLetra;
    private javax.swing.JLabel altoLetra;
    private javax.swing.JLabel anchoLetra;
    private javax.swing.JTextField campoAlto;
    private javax.swing.JTextField campoAncho;
    private javax.swing.JButton botFondo;
    private javax.swing.JTextField campoPrior;
    private javax.swing.JLabel prioridadLetra;
}