import herramientas.grafico.figuras.Figura;
import herramientas.grafico.figuras.Simple;
import herramientas.grafico.animaciones.Animacion;

import java.util.ArrayList;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JLabel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class CrearAnimEspecial extends JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private PanelAnimacion panelAnim;
    private boolean infinito;
    private ArrayList<Animacion> animaciones;

    public CrearAnimEspecial() {
        animaciones = new ArrayList<Animacion>();
        
        initComponents();
        String[]titulo= new String[]{"Animación","Posición Final"};
        modelo.setColumnIdentifiers(titulo);
        tablaAnim.setModel(modelo); 

        panelAnim = new PanelAnimacion();
        panelAnim.setSize(660,760);
        panelAnim.setLocation(0, 0);

        panelAni.removeAll();
        panelAni.add(panelAnim, BorderLayout.CENTER);
        panelAni.revalidate();
        panelAni.repaint();

        pack();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        buttonGroup1 = new ButtonGroup();
        back = new JPanel();
        headA = new JPanel();
        IcUserA = new JLabel();
        LogoA = new JLabel();
        botonInicio = new JPanel();
        IcHouseA = new JLabel();
        panelAni = new JPanel();
        setAnim = new JPanel();
        figuraLetra = new JLabel();
        jComboBoxFig = new JComboBox<>();
        AnimLetra = new JLabel();
        jComboBoxAnim = new JComboBox<>();
        pos = new JLabel();
        x = new JLabel();
        posX = new JTextField();
        separador1 = new JSeparator();
        y = new JLabel();
        posY = new JTextField();
        separador2 = new JSeparator();
        botAgregar = new JButton();
        botNuevo = new JButton();
        separador4 = new JSeparator();
        botElim = new JButton();
        botElimTodo = new JButton();
        jScrollPane1 = new JScrollPane();
        tablaAnim = new JTable();
        guardarLetra = new JLabel();
        nameAnimEsp = new JTextField();
        botonGuardar = new JPanel();
        guardarA = new JLabel();
        botonTerminar = new JPanel();
        terminarA = new JLabel();
        opcionFinita = new JRadioButton();
        opcionCiclada = new JRadioButton();
        botonVoz = new javax.swing.JButton();

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        back.setMinimumSize(new java.awt.Dimension(1000, 800));
        back.setPreferredSize(new java.awt.Dimension(1000, 800));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headA.setBackground(new java.awt.Color(0, 0, 0));
        headA.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        headA.setPreferredSize(new java.awt.Dimension(1000, 52));

        IcUserA.setIcon(new ImageIcon(getClass().getResource("/imagenes/people.png"))); // NOI18N
        IcUserA.setText("jLabel2");
        IcUserA.setAlignmentY(0.0F);
        IcUserA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LogoA.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LogoA.setForeground(new java.awt.Color(255, 255, 255));
        LogoA.setIcon(new ImageIcon(getClass().getResource("/imagenes/logo2.png"))); // NOI18N
        LogoA.setText("ANIMUSIC");

        botonInicio.setBackground(new java.awt.Color(0, 0, 0));
        botonInicio.setPreferredSize(new java.awt.Dimension(45, 32));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    botonInicioMouseClicked(evt);
                }
            });

        IcHouseA.setHorizontalAlignment(SwingConstants.CENTER);
        IcHouseA.setIcon(new ImageIcon(getClass().getResource("/imagenes/house2.png"))); // NOI18N
        IcHouseA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GroupLayout botonInicioLayout = new GroupLayout(botonInicio);
        botonInicio.setLayout(botonInicioLayout);
        botonInicioLayout.setHorizontalGroup(
            botonInicioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(botonInicioLayout.createSequentialGroup()
                .addComponent(IcHouseA)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        botonInicioLayout.setVerticalGroup(
            botonInicioLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(IcHouseA, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout headALayout = new GroupLayout(headA);
        headA.setLayout(headALayout);
        headALayout.setHorizontalGroup(
            headALayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, headALayout.createSequentialGroup()
                .addComponent(LogoA, GroupLayout.PREFERRED_SIZE, 126, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                .addComponent(botonInicio, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IcUserA, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        headALayout.setVerticalGroup(
            headALayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(headALayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(headALayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoA, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                    .addGroup(headALayout.createSequentialGroup()
                        .addGroup(headALayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(botonInicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(IcUserA, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        back.add(headA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        panelAni.setBackground(new java.awt.Color(65, 65, 67));
        panelAni.setForeground(new java.awt.Color(255, 255, 255));

        GroupLayout panelAniLayout = new GroupLayout(panelAni);
        panelAni.setLayout(panelAniLayout);
        panelAniLayout.setHorizontalGroup(
            panelAniLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        panelAniLayout.setVerticalGroup(
            panelAniLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        back.add(panelAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 660, 760));

        setAnim.setBackground(new java.awt.Color(65, 65, 67));
        setAnim.setBorder(BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setAnim.setForeground(new java.awt.Color(255, 255, 255));

        figuraLetra.setBackground(new java.awt.Color(240, 235, 221));
        figuraLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        figuraLetra.setForeground(new java.awt.Color(255, 255, 255));
        figuraLetra.setHorizontalAlignment(SwingConstants.CENTER);
        figuraLetra.setText("FIGURA:");
        figuraLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBoxFig.setBackground(new java.awt.Color(240, 235, 221));
        jComboBoxFig.setModel(new DefaultComboBoxModel<>(new String[] { ".", "Acordeon", "Corno", "Electrica", "Flauta", "Guitarra", "Mandolina", "Maracas", "Microfono", "Platillos", "Saxofon", "Tambor", "Teclado", "Trompeta", "Tuba", "Violin", "Xilofono" }));
        jComboBoxFig.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBoxFigActionPerformed(evt);
                }
            });

        AnimLetra.setBackground(new java.awt.Color(240, 235, 221));
        AnimLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        AnimLetra.setForeground(new java.awt.Color(255, 255, 255));
        AnimLetra.setHorizontalAlignment(SwingConstants.CENTER);
        AnimLetra.setText("ANIMACIÓN:");
        AnimLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBoxAnim.setBackground(new java.awt.Color(240, 235, 221));
        jComboBoxAnim.setModel(new DefaultComboBoxModel<>(new String[] { ".", "Caida Libre", "Rebote Horizontal", "Movimientos Horizontales", "Movimientos Laterales", "Trayectoria Cruz", "Trayectoria Cuadrada" }));
        jComboBoxAnim.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBoxAnimActionPerformed(evt);
                }
            });

        pos.setBackground(new java.awt.Color(240, 235, 221));
        pos.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        pos.setForeground(new java.awt.Color(255, 255, 255));
        pos.setHorizontalAlignment(SwingConstants.CENTER);
        pos.setText("POSICIÓN FINAL:");
        pos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        x.setBackground(new java.awt.Color(240, 235, 221));
        x.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        x.setForeground(new java.awt.Color(255, 255, 255));
        x.setHorizontalAlignment(SwingConstants.CENTER);
        x.setText("X:");
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        posX.setBackground(new java.awt.Color(65, 65, 67));
        posX.setForeground(new java.awt.Color(204, 204, 204));
        posX.setBorder(null);
        posX.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }
                
                public void keyReleased(KeyEvent e){}
                public void keyPressed(KeyEvent e){}
            });

        separador1.setBackground(new java.awt.Color(204, 204, 204));

        y.setBackground(new java.awt.Color(240, 235, 221));
        y.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        y.setForeground(new java.awt.Color(255, 255, 255));
        y.setHorizontalAlignment(SwingConstants.CENTER);
        y.setText("Y:");
        y.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        posY.setBackground(new java.awt.Color(65, 65, 67));
        posY.setForeground(new java.awt.Color(204, 204, 204));
        posY.setBorder(null);
        posY.addKeyListener(new KeyListener() {
                public void keyTyped(KeyEvent evt) {
                    Utils.validarCampoSoloDigito(evt);
                }
                
                public void keyReleased(KeyEvent e){}
                public void keyPressed(KeyEvent e){}
            });

        separador2.setBackground(new java.awt.Color(204, 204, 204));

        botAgregar.setBackground(new java.awt.Color(203, 182, 163));
        botAgregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botAgregar.setText("Agregar");
        botAgregar.setBorder(null);
        botAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botAgregar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botAgregarActionPerformed(evt);
                }
            });

        botNuevo.setBackground(new java.awt.Color(203, 182, 163));
        botNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botNuevo.setText("Nuevo");
        botNuevo.setBorder(null);
        botNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botNuevoActionPerformed(evt);
                }
            });

        separador4.setBackground(new java.awt.Color(204, 204, 204));

        botElim.setBackground(new java.awt.Color(203, 182, 163));
        botElim.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botElim.setText("Eliminar");
        botElim.setBorder(null);
        botElim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botElim.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botElimActionPerformed(evt);
                }
            });

        botElimTodo.setBackground(new java.awt.Color(203, 182, 163));
        botElimTodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botElimTodo.setText("Eliminar todo");
        botElimTodo.setBorder(null);
        botElimTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botElimTodo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botElimTodoActionPerformed(evt);
                }
            });

        tablaAnim.setBackground(new java.awt.Color(240, 235, 221));
        tablaAnim.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaAnim.setModel(new DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
        tablaAnim.setGridColor(new java.awt.Color(255, 255, 255));
        tablaAnim.setSelectionForeground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(tablaAnim);

        guardarLetra.setBackground(new java.awt.Color(240, 235, 221));
        guardarLetra.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        guardarLetra.setForeground(new java.awt.Color(255, 255, 255));
        guardarLetra.setHorizontalAlignment(SwingConstants.CENTER);
        guardarLetra.setText("Guardar como:");
        guardarLetra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nameAnimEsp.setBackground(new java.awt.Color(65, 65, 67));
        nameAnimEsp.setForeground(new java.awt.Color(204, 204, 204));
        nameAnimEsp.setText("Animacion");
        nameAnimEsp.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                nameAnimEspActionPerformed(evt);
            }
        });

        botonGuardar.setBackground(new java.awt.Color(211, 137, 124));
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    botonGuardarMouseClicked(evt);
                }
            });

        guardarA.setBackground(new java.awt.Color(240, 235, 221));
        guardarA.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        guardarA.setForeground(new java.awt.Color(255, 255, 255));
        guardarA.setHorizontalAlignment(SwingConstants.CENTER);
        guardarA.setText("GUARDAR");
        guardarA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GroupLayout botonGuardarLayout = new GroupLayout(botonGuardar);
        botonGuardar.setLayout(botonGuardarLayout);
        botonGuardarLayout.setHorizontalGroup(
            botonGuardarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(botonGuardarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(guardarA, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        botonGuardarLayout.setVerticalGroup(
            botonGuardarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, botonGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarA, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        );

        botonTerminar.setBackground(new java.awt.Color(203, 182, 163));
        botonTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    botonTerminarMouseClicked(evt);
                }
            });

        terminarA.setBackground(new java.awt.Color(240, 235, 221));
        terminarA.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        terminarA.setForeground(new java.awt.Color(255, 255, 255));
        terminarA.setHorizontalAlignment(SwingConstants.CENTER);
        terminarA.setText("TERMINAR");
        terminarA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        GroupLayout botonTerminarLayout = new GroupLayout(botonTerminar);
        botonTerminar.setLayout(botonTerminarLayout);
        botonTerminarLayout.setHorizontalGroup(
            botonTerminarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(botonTerminarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(terminarA, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        botonTerminarLayout.setVerticalGroup(
            botonTerminarLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, botonTerminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(terminarA, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(opcionFinita);
        opcionFinita.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        opcionFinita.setForeground(new java.awt.Color(255, 255, 255));
        opcionFinita.setText("Finita");
        opcionFinita.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    infinito = false;
                    if (panelAnim.getFiguras().size() > 0) panelAnim.getFigura(0).detenerAnimacion();
                }
            });

        buttonGroup1.add(opcionCiclada);
        opcionCiclada.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        opcionCiclada.setForeground(new java.awt.Color(255, 255, 255));
        opcionCiclada.setText("Ciclada");
        opcionCiclada.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    infinito = true;
                    if (panelAnim.getFiguras().size() > 0) panelAnim.getFigura(0).detenerAnimacion();
                }
            });

        
            
        botonVoz.setBackground(new java.awt.Color(203, 182, 163));
        botonVoz.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        botonVoz.setText("ON VOZ");
        botonVoz.setBorder(null);
        botonVoz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setAnimLayout = new javax.swing.GroupLayout(setAnim);
        setAnim.setLayout(setAnimLayout);
        setAnimLayout.setHorizontalGroup(
            setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador4)
            .addGroup(setAnimLayout.createSequentialGroup()
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                    .addComponent(guardarLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nameAnimEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(botAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(botNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(separador1)
                                    .addComponent(posX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(separador2)
                                    .addComponent(posY, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addComponent(pos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(setAnimLayout.createSequentialGroup()
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AnimLetra)
                                    .addComponent(figuraLetra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxFig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxAnim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                        .addComponent(botElim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(botElimTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                        .addComponent(opcionCiclada)
                        .addGap(18, 18, 18)
                        .addComponent(opcionFinita)
                        .addGap(97, 97, 97))))
        );
        setAnimLayout.setVerticalGroup(
            setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setAnimLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(figuraLetra)
                    .addComponent(jComboBoxFig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnimLetra)
                    .addComponent(jComboBoxAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos)
                    .addComponent(botonVoz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posX)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(setAnimLayout.createSequentialGroup()
                        .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(posY)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, setAnimLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botElim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botElimTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionCiclada)
                    .addComponent(opcionFinita))
                .addGap(28, 28, 28)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameAnimEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarLetra))
                .addGap(18, 18, 18)
                .addGroup(setAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonTerminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        back.add(setAnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 340, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>       

    private void botonCerrarSesMouseClicked(MouseEvent evt) {
        dispose();
        new Login().setVisible(true);
    }                                           

    private void botonInicioMouseClicked(MouseEvent evt) {                                         
        dispose();
        new Inicio().setVisible(true);
    }                                        

    private void nameAnimEspActionPerformed(MouseEvent evt) {
        if (nameAnimEsp.getText().equals("Animacion")) {
            nameAnimEsp.setText("");
            nameAnimEsp.setForeground(Color.white);
        }
    }                                           

    private void botonGuardarMouseClicked(MouseEvent evt) {
        Serializado.serializarAnimacion(crearAnimacion());
        JOptionPane.showMessageDialog(null, "Animacion Compuesta Creada", null, JOptionPane.INFORMATION_MESSAGE);
        dispose();
        new CrearAnimEspecial().setVisible(true);
    }                                         

    private void botonTerminarMouseClicked(MouseEvent evt) {
        if (panelAnim.getFiguras().size() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione una figura!", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Figura fig = panelAnim.getFigura(0);
        fig.setAnimacion(crearAnimacion());
        fig.animar();
    }
    
    private Animacion crearAnimacion() {
        return new Animacion(animaciones, infinito, nameAnimEsp.getText());
    }

    private void botElimActionPerformed(ActionEvent evt) {                                        
        int elim = tablaAnim.getSelectedRow();
        if(elim>=0){
            this.animaciones.remove(elim);
            modelo.removeRow(elim);
        }else{
            JOptionPane.showMessageDialog(null, "No hay datos que eliminar", null, JOptionPane.WARNING_MESSAGE);
        }
    }                                       

    private void botElimTodoActionPerformed(ActionEvent evt) {                                            
        int eliTotal = tablaAnim.getRowCount();
        
        for(int i=eliTotal-1;i>=0; i--){
            modelo.removeRow(i);
        }
        
        this.animaciones.clear();
    }                                           

    private void botNuevoActionPerformed(ActionEvent evt) {                                         
        posX.setText("");
        posY.setText("");
    }                                        

    private void botAgregarActionPerformed(ActionEvent evt) {
        if (posX.getText().equals("") || posY.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Posicion final no definida", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (jComboBoxFig.getSelectedItem().equals(".")) {
            JOptionPane.showMessageDialog(null, "Seleccione una figura!", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Figura f = panelAnim.getFigura(0);
        Animacion animacion = Utils.crearAnimacion(jComboBoxAnim.getSelectedItem().toString(), f.getPosicion());
        
        if (animacion == null) {
            JOptionPane.showMessageDialog(null, "Animacion no valida", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Point puntoFinal = new Point(Integer.parseInt(posX.getText()), Integer.parseInt(posY.getText()));
        animacion.setPuntoFinal(puntoFinal);
        this.animaciones.add(animacion);
        
        String [] agregar = new String[2];
        agregar[0]= jComboBoxAnim.getSelectedItem().toString();
        agregar[1]= posX.getText() + " - " + posY.getText();
        modelo.addRow(agregar);
    }                                          

    private void jComboBoxAnimActionPerformed(ActionEvent evt) {
        Animacion animacion = Utils.crearAnimacion((String) jComboBoxAnim.getSelectedItem(), null);
        if (animacion == null) return;
        Archivo.escribirEstadisticaAnimacion(animacion.getNombre());
    }

    private void jComboBoxFigActionPerformed(ActionEvent evt) {                                             
        if (panelAnim.getFiguras().size() > 0) panelAnim.borrarTodo();

        Figura figura = Utils.crearFigura(jComboBoxFig.getSelectedItem().toString(), null);
        figura.setPanel(panelAnim);
        panelAnim.agregarFigura(figura);
        
        if (figura instanceof Simple) return;
        Archivo.escribirEstadisticaFigura(figura.getNombre());
    }
    
    private void botonVozActionPerformed(java.awt.event.ActionEvent evt) {
        Utils.vozFiguras(jComboBoxFig);
    } 

    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAnimEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAnimEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAnimEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAnimEspecial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CrearAnimEspecial().setVisible(true);
                }
            });
    }

    private JLabel AnimLetra;
    private JLabel IcHouseA;
    private JLabel IcUserA;
    private JLabel LogoA;
    private JPanel back;
    private JButton botAgregar;
    private JButton botElim;
    private JButton botElimTodo;
    private JButton botNuevo;
    private JButton botonVoz;
    private JPanel botonCerrarSes;
    private JPanel botonGuardar;
    private JPanel botonInicio;
    private JPanel botonTerminar;
    private JLabel cerrarSes;
    private JLabel figuraLetra;
    private JLabel guardarA;
    private JLabel guardarLetra;
    private JPanel headA;
    private JComboBox<String> jComboBoxAnim;
    private JComboBox<String> jComboBoxFig;
    private JScrollPane jScrollPane1;
    private JTextField nameAnimEsp;
    private JPanel panelAni;
    private JLabel pos;
    private JTextField posX;
    private JTextField posY;
    private JSeparator separador1;
    private JSeparator separador2;
    private JSeparator separador4;
    private JPanel setAnim;
    private JTable tablaAnim;
    private JLabel terminarA;
    private JLabel x;
    private JLabel y;
    private ButtonGroup buttonGroup1;
    private JRadioButton opcionCiclada;
    private JRadioButton opcionFinita;
}
