import java.awt.Color;

public class Inicio extends javax.swing.JFrame {
    private javax.swing.JLabel IcUserA, LogoA,cerrarSes;
    private javax.swing.JPanel back,botCrearAnim,botEmpezarProy,botVerEst, botonCerrarSes,headA,jPanel2;
    private javax.swing.JLabel imgDisco,jLabel,jLabel1,jLabel2,jLabel3;
 
    public Inicio() {
        initComponents();
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // setPreferredSize(new java.awt.Dimension(1000, 800));
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        back = new javax.swing.JPanel();
        headA = new javax.swing.JPanel();
        IcUserA = new javax.swing.JLabel();
        botonCerrarSes = new javax.swing.JPanel();
        cerrarSes = new javax.swing.JLabel();
        LogoA = new javax.swing.JLabel();
        imgDisco = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        botEmpezarProy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botVerEst = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botCrearAnim = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setMinimumSize(new java.awt.Dimension(1000, 800));
        back.setPreferredSize(new java.awt.Dimension(1000, 800));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headA.setBackground(new java.awt.Color(0, 0, 0));
        headA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        headA.setPreferredSize(new java.awt.Dimension(1000, 52));

        IcUserA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/people.png"))); // NOI18N
        IcUserA.setText("jLabel2");
        IcUserA.setAlignmentY(0.0F);
        IcUserA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonCerrarSes.setBackground(new java.awt.Color(203, 182, 163));
        botonCerrarSes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarSesMouseClicked(evt);
            }
        });

        cerrarSes.setBackground(new java.awt.Color(240, 235, 221));
        cerrarSes.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        cerrarSes.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarSes.setText("Cerrar Sesión");
        cerrarSes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout botonCerrarSesLayout = new javax.swing.GroupLayout(botonCerrarSes);
        botonCerrarSes.setLayout(botonCerrarSesLayout);
        botonCerrarSesLayout.setHorizontalGroup(
            botonCerrarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonCerrarSesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarSes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        botonCerrarSesLayout.setVerticalGroup(
            botonCerrarSesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrarSes, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        LogoA.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LogoA.setForeground(new java.awt.Color(255, 255, 255));
        LogoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo2.png"))); // NOI18N
        LogoA.setText("ANIMUSIC");

        javax.swing.GroupLayout headALayout = new javax.swing.GroupLayout(headA);
        headA.setLayout(headALayout);
        headALayout.setHorizontalGroup(
            headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headALayout.createSequentialGroup()
                .addComponent(LogoA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                .addComponent(botonCerrarSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IcUserA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headALayout.setVerticalGroup(
            headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headALayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogoA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headALayout.createSequentialGroup()
                        .addGroup(headALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCerrarSes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IcUserA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        back.add(headA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        imgDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoIni.jpg"))); // NOI18N
        back.add(imgDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 760));

        jPanel2.setBackground(new java.awt.Color(219, 218, 188));

        jLabel.setFont(new java.awt.Font("Roboto Black", 3, 48)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("¡BIENVENIDO!");

        botEmpezarProy.setBackground(new java.awt.Color(211, 137, 124));
        botEmpezarProy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botEmpezarProy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botEmpezarProyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botEmpezarProyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botEmpezarProyMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPEZAR PROYECTO");

        javax.swing.GroupLayout botEmpezarProyLayout = new javax.swing.GroupLayout(botEmpezarProy);
        botEmpezarProy.setLayout(botEmpezarProyLayout);
        botEmpezarProyLayout.setHorizontalGroup(
            botEmpezarProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botEmpezarProyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        botEmpezarProyLayout.setVerticalGroup(
            botEmpezarProyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        botVerEst.setBackground(new java.awt.Color(211, 137, 124));
        botVerEst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botVerEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botVerEstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botVerEstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botVerEstMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VER ESTADÍSTICAS");

        javax.swing.GroupLayout botVerEstLayout = new javax.swing.GroupLayout(botVerEst);
        botVerEst.setLayout(botVerEstLayout);
        botVerEstLayout.setHorizontalGroup(
            botVerEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botVerEstLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        botVerEstLayout.setVerticalGroup(
            botVerEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        botCrearAnim.setBackground(new java.awt.Color(211, 137, 124));
        botCrearAnim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botCrearAnim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botCrearAnimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botCrearAnimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botCrearAnimMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREAR ANIMACIONES");

        javax.swing.GroupLayout botCrearAnimLayout = new javax.swing.GroupLayout(botCrearAnim);
        botCrearAnim.setLayout(botCrearAnimLayout);
        botCrearAnimLayout.setHorizontalGroup(
            botCrearAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botCrearAnimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        botCrearAnimLayout.setVerticalGroup(
            botCrearAnimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botCrearAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botVerEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(171, Short.MAX_VALUE)
                    .addComponent(botEmpezarProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(140, 140, 140)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(257, 257, 257)
                .addComponent(botVerEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(botCrearAnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(botEmpezarProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );

        back.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 550, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    private void botonCerrarSesMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
        new Login().setVisible(true);
    }                                           

    private void botVerEstMouseClicked(java.awt.event.MouseEvent evt) {                                       
        dispose();
        new Estadistica().setVisible(true);
    }                                      

    private void botEmpezarProyMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
        new CrearPublicidad().setVisible(true);
    }                                           

    private void botCrearAnimMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
        new CrearAnimacion().setVisible(true);
    }                                         

    private void botEmpezarProyMouseEntered(java.awt.event.MouseEvent evt) {                                            
        botEmpezarProy.setBackground(new Color(203,182,163));
    }                                           

    private void botEmpezarProyMouseExited(java.awt.event.MouseEvent evt) {                                           
        botEmpezarProy.setBackground(new Color(211,137,124));
    }                                          

    private void botVerEstMouseEntered(java.awt.event.MouseEvent evt) {                                       
        botVerEst.setBackground(new Color(203,182,163));
    }                                      

    private void botVerEstMouseExited(java.awt.event.MouseEvent evt) {                                      
        botVerEst.setBackground(new Color(211,137,124));
    }                                     

    private void botCrearAnimMouseEntered(java.awt.event.MouseEvent evt) {                                          
        botCrearAnim.setBackground(new Color(203,182,163));
    }                                         

    private void botCrearAnimMouseExited(java.awt.event.MouseEvent evt) {                                         
        botCrearAnim.setBackground(new Color(211,137,124));
    }                                        

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
                  
}