import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;

import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.UIManager;

import java.util.HashMap;

import org.netbeans.lib.awtextra.AbsoluteLayout;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public class Login extends JFrame {
    private JLabel Contrasena, ImagenIz, IniSes, Logo, Usuario, jLabel1, jLabel2;
    private JSeparator Linea1, Linea2;
    private JPanel botEntrar, jPanel1, botReg;
    private JPasswordField campoContra;
    private JTextField campoUsuario;
    
    
    public Login() {
        // Serializado.iniciar();  // Reinicia el archivo de serializacion
        Archivo.borrarEstadisticas();
        
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1000, 800));
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Login().setVisible(true);
                }
            });
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagenIz = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        IniSes = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        Linea1 = new javax.swing.JSeparator();
        Contrasena = new javax.swing.JLabel();
        campoContra = new javax.swing.JPasswordField();
        Linea2 = new javax.swing.JSeparator();
        botReg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botEntrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenIz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vintage.png"))); // NOI18N
        ImagenIz.setText("jLabel1");
        jPanel1.add(ImagenIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 800));

        Logo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Logo.setIcon(new ImageIcon(getClass().getResource("/imagenes/icons8-musica-bubbles-96.png"))); // NOI18N
        Logo.setText("ANIMUSIC");
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 260, 90));

        IniSes.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        IniSes.setText("INICIAR SESIÓN");
        jPanel1.add(IniSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Usuario.setText("USUARIO");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        campoUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Ingrese su nombre de Usuario");
        campoUsuario.setBorder(null);
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoUsuarioMousePressed(evt);
            }
        });
        
        jPanel1.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));
        jPanel1.add(Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 320, 20));

        Contrasena.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Contrasena.setText("CONTRASEÑA");
        jPanel1.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        campoContra.setForeground(new java.awt.Color(204, 204, 204));
        campoContra.setText("********");
        campoContra.setBorder(null);
        campoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campoContraMousePressed(evt);
            }
        });
        
        jPanel1.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));
        jPanel1.add(Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 320, 20));

        botReg.setBackground(new java.awt.Color(211, 137, 124));
        botReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botRegMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRARSE");
        botReg.add(jLabel2);

        jPanel1.add(botReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 140, 40));

        botEntrar.setBackground(new java.awt.Color(94, 127, 110));
        botEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botEntrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        botEntrar.add(jLabel1);

        jPanel1.add(botEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>  


    private void botEntrarMouseClicked(MouseEvent evt) {
        HashMap<String, String> usuarios = Archivo.cargarUsuarios();
        
        if (usuarios.containsKey(campoUsuario.getText())) {
            if (usuarios.get(campoUsuario.getText()).equals(new String(campoContra.getPassword()))) {
                dispose();
                new Inicio().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "El usuario o la contraseña no coinciden", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el usuario!", null, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void botRegMouseClicked(MouseEvent evt) {
        //dispose();
        new Registro().setVisible(true);
    }

    private void campoUsuarioMousePressed(MouseEvent evt) {                                          
        if (campoUsuario.getText().equals("Ingrese su nombre de Usuario")) {
            campoUsuario.setText("");
            campoUsuario.setForeground(Color.black);
        }
        if (String.valueOf(campoContra.getPassword()).isEmpty()) {
            campoContra.setText("********");
            campoContra.setForeground(Color.gray);
        }
    }                                         

    private void campoContraMousePressed(MouseEvent evt) {                                         
        if (String.valueOf(campoContra.getPassword()).equals("********")) {
            campoContra.setText("");
            campoContra.setForeground(Color.black);
        }
        if (campoUsuario.getText().isEmpty()) {
            campoUsuario.setText("Ingrese su nombre de Usuario");
            campoUsuario.setForeground(Color.gray);
        }
    }                                        
}
