import java.awt.Color;
import javax.swing.ImageIcon;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Desktop
 */
public class Registro extends javax.swing.JDialog {
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel CrearCuenta;
    private javax.swing.JLabel ImagenIz;
    private javax.swing.JSeparator Linea1;
    private javax.swing.JSeparator Linea2;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Reg;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JPanel botRegis;
    private javax.swing.JTextField campoContra;
    private javax.swing.JTextField campoUser;
    private javax.swing.JPanel jPanel1;
    private HashMap<String, String> usuarios;
    /**
     * Creates new form Login
     */
    public Registro() {
        setModal(true);
        initComponents();
        pack();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagenIz = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        CrearCuenta = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        campoUser = new javax.swing.JTextField();
        Linea1 = new javax.swing.JSeparator();
        Contraseña = new javax.swing.JLabel();
        campoContra = new javax.swing.JTextField();
        Linea2 = new javax.swing.JSeparator();
        botRegis = new javax.swing.JPanel();
        Reg = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenIz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vintage.png"))); // NOI18N
        ImagenIz.setText("jLabel1");
        jPanel1.add(ImagenIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 800));

        Logo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        Logo.setIcon(new ImageIcon(getClass().getResource("/imagenes/icons8-musica-bubbles-96.png"))); // NOI18N
        Logo.setText("ANIMUSIC");
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 260, 90));

        CrearCuenta.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        CrearCuenta.setText("CREAR CUENTA");
        jPanel1.add(CrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        Usuario1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Usuario1.setText("USUARIO");
        jPanel1.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        campoUser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoUser.setForeground(new java.awt.Color(153, 153, 153));
        campoUser.setText("Ingrese un nombre de Usuario");
        campoUser.setBorder(null);
        campoUser.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    campoUserMousePressed(evt);
                }
            });
            
        jPanel1.add(campoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));
        jPanel1.add(Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 320, 20));

        Contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Contraseña.setText("CONTRASEÑA");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        campoContra.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        campoContra.setForeground(new java.awt.Color(153, 153, 153));
        campoContra.setText("Ingrese una Contraseña");
        campoContra.setBorder(null);
        campoContra.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    campoContraMousePressed(evt);
                }
            });
            
        jPanel1.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, -1, -1));
        jPanel1.add(Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 320, 20));

        botRegis.setBackground(new java.awt.Color(211, 137, 124));
        botRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botRegis.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    botRegisMouseClicked(evt);
                }
            });

        Reg.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Reg.setForeground(new java.awt.Color(255, 255, 255));
        Reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reg.setText("REGISTRARSE");

        javax.swing.GroupLayout botRegisLayout = new javax.swing.GroupLayout(botRegis);
        botRegis.setLayout(botRegisLayout);
        botRegisLayout.setHorizontalGroup(
            botRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botRegisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reg, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        botRegisLayout.setVerticalGroup(
            botRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Reg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(botRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    private void campoContraMousePressed(java.awt.event.MouseEvent evt) {                                         
        if (campoContra.getText().equals("Ingrese una Contraseña")) {
            campoContra.setText("");
            campoContra.setForeground(Color.black);
        }

        if (campoUser.getText().isEmpty()) {
            campoUser.setText("Ingrese un nombre de Usuario");
            campoUser.setForeground(Color.gray);
        }
    }                                        

    private void campoUserMousePressed(java.awt.event.MouseEvent evt) {                                       
        if (campoUser.getText().equals("Ingrese un nombre de Usuario")) {
            campoUser.setText("");
            campoUser.setForeground(Color.black);
        }
        if (campoContra.getText().isEmpty()){
            campoContra.setText("Ingrese una Contraseña");
            campoContra.setForeground(Color.gray);
        }
    }                                      

    private void botRegisMouseClicked(java.awt.event.MouseEvent evt) {
        String user = campoUser.getText(), pass = campoContra.getText();
        
        if (user.equals("Ingrese un nombre de Usuario") || user.isEmpty() || pass.isEmpty()
                || pass.equals("Ingrese una Contraseña"))
        {
            JOptionPane.showMessageDialog(null, "Llene los campos!", null, JOptionPane.WARNING_MESSAGE);
            return;
        }
                
        if (Archivo.cargarUsuarios().containsKey(user)) {
            JOptionPane.showMessageDialog(null, "El usuario ya existe", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.util.regex.Pattern pat = java.util.regex.Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{5,8}$");
        java.util.regex.Matcher mat = pat.matcher(pass);
        
        if (!mat.matches()) {
            JOptionPane.showMessageDialog(null, "Contraseña no valida! Debe contener un numero, una letra minuscula y una mayuscula porlomenos", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String s = user + "=" + pass;
        Archivo.registrarUsuario(s);
        dispose();
        new Login().setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Registro().setVisible(true);
                }
            });
    }

}

